// Code generated by ent, DO NOT EDIT.

package ideamessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldDeletedAt, v))
}

// AuthorID applies equality check predicate on the "author_id" field. It's identical to AuthorIDEQ.
func AuthorID(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorName applies equality check predicate on the "author_name" field. It's identical to AuthorNameEQ.
func AuthorName(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldAuthorName, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldTitle, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldContent, v))
}

// AdminReply applies equality check predicate on the "admin_reply" field. It's identical to AdminReplyEQ.
func AdminReply(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldAdminReply, v))
}

// AdminReplyBy applies equality check predicate on the "admin_reply_by" field. It's identical to AdminReplyByEQ.
func AdminReplyBy(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldAdminReplyBy, v))
}

// AdminReplyAt applies equality check predicate on the "admin_reply_at" field. It's identical to AdminReplyAtEQ.
func AdminReplyAt(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldAdminReplyAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotNull(FieldDeletedAt))
}

// AuthorIDEQ applies the EQ predicate on the "author_id" field.
func AuthorIDEQ(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorIDNEQ applies the NEQ predicate on the "author_id" field.
func AuthorIDNEQ(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNEQ(FieldAuthorID, v))
}

// AuthorIDIn applies the In predicate on the "author_id" field.
func AuthorIDIn(vs ...int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIn(FieldAuthorID, vs...))
}

// AuthorIDNotIn applies the NotIn predicate on the "author_id" field.
func AuthorIDNotIn(vs ...int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotIn(FieldAuthorID, vs...))
}

// AuthorIDGT applies the GT predicate on the "author_id" field.
func AuthorIDGT(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGT(FieldAuthorID, v))
}

// AuthorIDGTE applies the GTE predicate on the "author_id" field.
func AuthorIDGTE(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGTE(FieldAuthorID, v))
}

// AuthorIDLT applies the LT predicate on the "author_id" field.
func AuthorIDLT(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLT(FieldAuthorID, v))
}

// AuthorIDLTE applies the LTE predicate on the "author_id" field.
func AuthorIDLTE(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLTE(FieldAuthorID, v))
}

// AuthorNameEQ applies the EQ predicate on the "author_name" field.
func AuthorNameEQ(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldAuthorName, v))
}

// AuthorNameNEQ applies the NEQ predicate on the "author_name" field.
func AuthorNameNEQ(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNEQ(FieldAuthorName, v))
}

// AuthorNameIn applies the In predicate on the "author_name" field.
func AuthorNameIn(vs ...string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIn(FieldAuthorName, vs...))
}

// AuthorNameNotIn applies the NotIn predicate on the "author_name" field.
func AuthorNameNotIn(vs ...string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotIn(FieldAuthorName, vs...))
}

// AuthorNameGT applies the GT predicate on the "author_name" field.
func AuthorNameGT(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGT(FieldAuthorName, v))
}

// AuthorNameGTE applies the GTE predicate on the "author_name" field.
func AuthorNameGTE(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGTE(FieldAuthorName, v))
}

// AuthorNameLT applies the LT predicate on the "author_name" field.
func AuthorNameLT(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLT(FieldAuthorName, v))
}

// AuthorNameLTE applies the LTE predicate on the "author_name" field.
func AuthorNameLTE(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLTE(FieldAuthorName, v))
}

// AuthorNameContains applies the Contains predicate on the "author_name" field.
func AuthorNameContains(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldContains(FieldAuthorName, v))
}

// AuthorNameHasPrefix applies the HasPrefix predicate on the "author_name" field.
func AuthorNameHasPrefix(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldHasPrefix(FieldAuthorName, v))
}

// AuthorNameHasSuffix applies the HasSuffix predicate on the "author_name" field.
func AuthorNameHasSuffix(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldHasSuffix(FieldAuthorName, v))
}

// AuthorNameEqualFold applies the EqualFold predicate on the "author_name" field.
func AuthorNameEqualFold(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEqualFold(FieldAuthorName, v))
}

// AuthorNameContainsFold applies the ContainsFold predicate on the "author_name" field.
func AuthorNameContainsFold(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldContainsFold(FieldAuthorName, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldContainsFold(FieldTitle, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldContainsFold(FieldContent, v))
}

// AdminReplyEQ applies the EQ predicate on the "admin_reply" field.
func AdminReplyEQ(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldAdminReply, v))
}

// AdminReplyNEQ applies the NEQ predicate on the "admin_reply" field.
func AdminReplyNEQ(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNEQ(FieldAdminReply, v))
}

// AdminReplyIn applies the In predicate on the "admin_reply" field.
func AdminReplyIn(vs ...string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIn(FieldAdminReply, vs...))
}

// AdminReplyNotIn applies the NotIn predicate on the "admin_reply" field.
func AdminReplyNotIn(vs ...string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotIn(FieldAdminReply, vs...))
}

// AdminReplyGT applies the GT predicate on the "admin_reply" field.
func AdminReplyGT(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGT(FieldAdminReply, v))
}

// AdminReplyGTE applies the GTE predicate on the "admin_reply" field.
func AdminReplyGTE(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGTE(FieldAdminReply, v))
}

// AdminReplyLT applies the LT predicate on the "admin_reply" field.
func AdminReplyLT(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLT(FieldAdminReply, v))
}

// AdminReplyLTE applies the LTE predicate on the "admin_reply" field.
func AdminReplyLTE(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLTE(FieldAdminReply, v))
}

// AdminReplyContains applies the Contains predicate on the "admin_reply" field.
func AdminReplyContains(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldContains(FieldAdminReply, v))
}

// AdminReplyHasPrefix applies the HasPrefix predicate on the "admin_reply" field.
func AdminReplyHasPrefix(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldHasPrefix(FieldAdminReply, v))
}

// AdminReplyHasSuffix applies the HasSuffix predicate on the "admin_reply" field.
func AdminReplyHasSuffix(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldHasSuffix(FieldAdminReply, v))
}

// AdminReplyIsNil applies the IsNil predicate on the "admin_reply" field.
func AdminReplyIsNil() predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIsNull(FieldAdminReply))
}

// AdminReplyNotNil applies the NotNil predicate on the "admin_reply" field.
func AdminReplyNotNil() predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotNull(FieldAdminReply))
}

// AdminReplyEqualFold applies the EqualFold predicate on the "admin_reply" field.
func AdminReplyEqualFold(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEqualFold(FieldAdminReply, v))
}

// AdminReplyContainsFold applies the ContainsFold predicate on the "admin_reply" field.
func AdminReplyContainsFold(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldContainsFold(FieldAdminReply, v))
}

// AdminReplyByEQ applies the EQ predicate on the "admin_reply_by" field.
func AdminReplyByEQ(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldAdminReplyBy, v))
}

// AdminReplyByNEQ applies the NEQ predicate on the "admin_reply_by" field.
func AdminReplyByNEQ(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNEQ(FieldAdminReplyBy, v))
}

// AdminReplyByIn applies the In predicate on the "admin_reply_by" field.
func AdminReplyByIn(vs ...int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIn(FieldAdminReplyBy, vs...))
}

// AdminReplyByNotIn applies the NotIn predicate on the "admin_reply_by" field.
func AdminReplyByNotIn(vs ...int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotIn(FieldAdminReplyBy, vs...))
}

// AdminReplyByGT applies the GT predicate on the "admin_reply_by" field.
func AdminReplyByGT(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGT(FieldAdminReplyBy, v))
}

// AdminReplyByGTE applies the GTE predicate on the "admin_reply_by" field.
func AdminReplyByGTE(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGTE(FieldAdminReplyBy, v))
}

// AdminReplyByLT applies the LT predicate on the "admin_reply_by" field.
func AdminReplyByLT(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLT(FieldAdminReplyBy, v))
}

// AdminReplyByLTE applies the LTE predicate on the "admin_reply_by" field.
func AdminReplyByLTE(v int64) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLTE(FieldAdminReplyBy, v))
}

// AdminReplyByIsNil applies the IsNil predicate on the "admin_reply_by" field.
func AdminReplyByIsNil() predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIsNull(FieldAdminReplyBy))
}

// AdminReplyByNotNil applies the NotNil predicate on the "admin_reply_by" field.
func AdminReplyByNotNil() predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotNull(FieldAdminReplyBy))
}

// AdminReplyAtEQ applies the EQ predicate on the "admin_reply_at" field.
func AdminReplyAtEQ(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldAdminReplyAt, v))
}

// AdminReplyAtNEQ applies the NEQ predicate on the "admin_reply_at" field.
func AdminReplyAtNEQ(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNEQ(FieldAdminReplyAt, v))
}

// AdminReplyAtIn applies the In predicate on the "admin_reply_at" field.
func AdminReplyAtIn(vs ...time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIn(FieldAdminReplyAt, vs...))
}

// AdminReplyAtNotIn applies the NotIn predicate on the "admin_reply_at" field.
func AdminReplyAtNotIn(vs ...time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotIn(FieldAdminReplyAt, vs...))
}

// AdminReplyAtGT applies the GT predicate on the "admin_reply_at" field.
func AdminReplyAtGT(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGT(FieldAdminReplyAt, v))
}

// AdminReplyAtGTE applies the GTE predicate on the "admin_reply_at" field.
func AdminReplyAtGTE(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGTE(FieldAdminReplyAt, v))
}

// AdminReplyAtLT applies the LT predicate on the "admin_reply_at" field.
func AdminReplyAtLT(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLT(FieldAdminReplyAt, v))
}

// AdminReplyAtLTE applies the LTE predicate on the "admin_reply_at" field.
func AdminReplyAtLTE(v time.Time) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLTE(FieldAdminReplyAt, v))
}

// AdminReplyAtIsNil applies the IsNil predicate on the "admin_reply_at" field.
func AdminReplyAtIsNil() predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIsNull(FieldAdminReplyAt))
}

// AdminReplyAtNotNil applies the NotNil predicate on the "admin_reply_at" field.
func AdminReplyAtNotNil() predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotNull(FieldAdminReplyAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IdeaMessage) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IdeaMessage) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IdeaMessage) predicate.IdeaMessage {
	return predicate.IdeaMessage(sql.NotPredicates(p))
}
