// Code generated by ent, DO NOT EDIT.

package mediaproductprice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldProductID, v))
}

// Operation applies equality check predicate on the "operation" field. It's identical to OperationEQ.
func Operation(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldOperation, v))
}

// SpecKey applies equality check predicate on the "spec_key" field. It's identical to SpecKeyEQ.
func SpecKey(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldSpecKey, v))
}

// UnitPriceUsd applies equality check predicate on the "unit_price_usd" field. It's identical to UnitPriceUsdEQ.
func UnitPriceUsd(v *decimal.Decimal) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldUnitPriceUsd, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldCurrency, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldVersion, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int64) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNotIn(FieldProductID, vs...))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNotIn(FieldOperation, vs...))
}

// OperationGT applies the GT predicate on the "operation" field.
func OperationGT(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGT(FieldOperation, v))
}

// OperationGTE applies the GTE predicate on the "operation" field.
func OperationGTE(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGTE(FieldOperation, v))
}

// OperationLT applies the LT predicate on the "operation" field.
func OperationLT(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLT(FieldOperation, v))
}

// OperationLTE applies the LTE predicate on the "operation" field.
func OperationLTE(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLTE(FieldOperation, v))
}

// OperationContains applies the Contains predicate on the "operation" field.
func OperationContains(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldContains(FieldOperation, v))
}

// OperationHasPrefix applies the HasPrefix predicate on the "operation" field.
func OperationHasPrefix(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldHasPrefix(FieldOperation, v))
}

// OperationHasSuffix applies the HasSuffix predicate on the "operation" field.
func OperationHasSuffix(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldHasSuffix(FieldOperation, v))
}

// OperationEqualFold applies the EqualFold predicate on the "operation" field.
func OperationEqualFold(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEqualFold(FieldOperation, v))
}

// OperationContainsFold applies the ContainsFold predicate on the "operation" field.
func OperationContainsFold(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldContainsFold(FieldOperation, v))
}

// SpecKeyEQ applies the EQ predicate on the "spec_key" field.
func SpecKeyEQ(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldSpecKey, v))
}

// SpecKeyNEQ applies the NEQ predicate on the "spec_key" field.
func SpecKeyNEQ(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNEQ(FieldSpecKey, v))
}

// SpecKeyIn applies the In predicate on the "spec_key" field.
func SpecKeyIn(vs ...string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldIn(FieldSpecKey, vs...))
}

// SpecKeyNotIn applies the NotIn predicate on the "spec_key" field.
func SpecKeyNotIn(vs ...string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNotIn(FieldSpecKey, vs...))
}

// SpecKeyGT applies the GT predicate on the "spec_key" field.
func SpecKeyGT(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGT(FieldSpecKey, v))
}

// SpecKeyGTE applies the GTE predicate on the "spec_key" field.
func SpecKeyGTE(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGTE(FieldSpecKey, v))
}

// SpecKeyLT applies the LT predicate on the "spec_key" field.
func SpecKeyLT(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLT(FieldSpecKey, v))
}

// SpecKeyLTE applies the LTE predicate on the "spec_key" field.
func SpecKeyLTE(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLTE(FieldSpecKey, v))
}

// SpecKeyContains applies the Contains predicate on the "spec_key" field.
func SpecKeyContains(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldContains(FieldSpecKey, v))
}

// SpecKeyHasPrefix applies the HasPrefix predicate on the "spec_key" field.
func SpecKeyHasPrefix(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldHasPrefix(FieldSpecKey, v))
}

// SpecKeyHasSuffix applies the HasSuffix predicate on the "spec_key" field.
func SpecKeyHasSuffix(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldHasSuffix(FieldSpecKey, v))
}

// SpecKeyEqualFold applies the EqualFold predicate on the "spec_key" field.
func SpecKeyEqualFold(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEqualFold(FieldSpecKey, v))
}

// SpecKeyContainsFold applies the ContainsFold predicate on the "spec_key" field.
func SpecKeyContainsFold(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldContainsFold(FieldSpecKey, v))
}

// UnitPriceUsdEQ applies the EQ predicate on the "unit_price_usd" field.
func UnitPriceUsdEQ(v *decimal.Decimal) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldUnitPriceUsd, v))
}

// UnitPriceUsdNEQ applies the NEQ predicate on the "unit_price_usd" field.
func UnitPriceUsdNEQ(v *decimal.Decimal) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNEQ(FieldUnitPriceUsd, v))
}

// UnitPriceUsdIn applies the In predicate on the "unit_price_usd" field.
func UnitPriceUsdIn(vs ...*decimal.Decimal) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldIn(FieldUnitPriceUsd, vs...))
}

// UnitPriceUsdNotIn applies the NotIn predicate on the "unit_price_usd" field.
func UnitPriceUsdNotIn(vs ...*decimal.Decimal) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNotIn(FieldUnitPriceUsd, vs...))
}

// UnitPriceUsdGT applies the GT predicate on the "unit_price_usd" field.
func UnitPriceUsdGT(v *decimal.Decimal) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGT(FieldUnitPriceUsd, v))
}

// UnitPriceUsdGTE applies the GTE predicate on the "unit_price_usd" field.
func UnitPriceUsdGTE(v *decimal.Decimal) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGTE(FieldUnitPriceUsd, v))
}

// UnitPriceUsdLT applies the LT predicate on the "unit_price_usd" field.
func UnitPriceUsdLT(v *decimal.Decimal) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLT(FieldUnitPriceUsd, v))
}

// UnitPriceUsdLTE applies the LTE predicate on the "unit_price_usd" field.
func UnitPriceUsdLTE(v *decimal.Decimal) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLTE(FieldUnitPriceUsd, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldContainsFold(FieldCurrency, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldContainsFold(FieldVersion, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.FieldNEQ(FieldEnabled, v))
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.MediaProductPrice {
	return predicate.MediaProductPrice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.MediaProduct) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaProductPrice) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaProductPrice) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaProductPrice) predicate.MediaProductPrice {
	return predicate.MediaProductPrice(sql.NotPredicates(p))
}
