// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/generationjob"
	"github.com/shopspring/decimal"
)

// GenerationJob is the model entity for the GenerationJob schema.
type GenerationJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID string `json:"public_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Modality holds the value of the "modality" field.
	Modality string `json:"modality,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// UpstreamGenerationID holds the value of the "upstream_generation_id" field.
	UpstreamGenerationID *string `json:"upstream_generation_id,omitempty"`
	// Status holds the value of the "status" field.
	Status generationjob.Status `json:"status,omitempty"`
	// UpstreamStatus holds the value of the "upstream_status" field.
	UpstreamStatus *string `json:"upstream_status,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash string `json:"request_hash,omitempty"`
	// RequestPayload holds the value of the "request_payload" field.
	RequestPayload map[string]interface{} `json:"request_payload,omitempty"`
	// ResultPayload holds the value of the "result_payload" field.
	ResultPayload map[string]interface{} `json:"result_payload,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// OutputCount holds the value of the "output_count" field.
	OutputCount int `json:"output_count,omitempty"`
	// ActualUpstreamCostAmount holds the value of the "actual_upstream_cost_amount" field.
	ActualUpstreamCostAmount *decimal.Decimal `json:"actual_upstream_cost_amount,omitempty"`
	// ActualUpstreamCostUnit holds the value of the "actual_upstream_cost_unit" field.
	ActualUpstreamCostUnit *string `json:"actual_upstream_cost_unit,omitempty"`
	// CustomerCost holds the value of the "customer_cost" field.
	CustomerCost *decimal.Decimal `json:"customer_cost,omitempty"`
	// BillingStatus holds the value of the "billing_status" field.
	BillingStatus generationjob.BillingStatus `json:"billing_status,omitempty"`
	// BillingReference holds the value of the "billing_reference" field.
	BillingReference *string `json:"billing_reference,omitempty"`
	// PollAttempts holds the value of the "poll_attempts" field.
	PollAttempts int `json:"poll_attempts,omitempty"`
	// NextPollAt holds the value of the "next_poll_at" field.
	NextPollAt *time.Time `json:"next_poll_at,omitempty"`
	// LastPolledAt holds the value of the "last_polled_at" field.
	LastPolledAt *time.Time `json:"last_polled_at,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// FailedAt holds the value of the "failed_at" field.
	FailedAt     *time.Time `json:"failed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GenerationJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case generationjob.FieldActualUpstreamCostAmount, generationjob.FieldCustomerCost:
			values[i] = &sql.NullScanner{S: new(decimal.Decimal)}
		case generationjob.FieldRequestPayload, generationjob.FieldResultPayload:
			values[i] = new([]byte)
		case generationjob.FieldID, generationjob.FieldUserID, generationjob.FieldAPIKeyID, generationjob.FieldGroupID, generationjob.FieldAccountID, generationjob.FieldOutputCount, generationjob.FieldPollAttempts:
			values[i] = new(sql.NullInt64)
		case generationjob.FieldPublicID, generationjob.FieldProvider, generationjob.FieldModality, generationjob.FieldModel, generationjob.FieldUpstreamModel, generationjob.FieldUpstreamGenerationID, generationjob.FieldStatus, generationjob.FieldUpstreamStatus, generationjob.FieldRequestHash, generationjob.FieldErrorCode, generationjob.FieldErrorMessage, generationjob.FieldActualUpstreamCostUnit, generationjob.FieldBillingStatus, generationjob.FieldBillingReference:
			values[i] = new(sql.NullString)
		case generationjob.FieldCreatedAt, generationjob.FieldUpdatedAt, generationjob.FieldNextPollAt, generationjob.FieldLastPolledAt, generationjob.FieldSubmittedAt, generationjob.FieldStartedAt, generationjob.FieldCompletedAt, generationjob.FieldFailedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GenerationJob fields.
func (_m *GenerationJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case generationjob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case generationjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case generationjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case generationjob.FieldPublicID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value.Valid {
				_m.PublicID = value.String
			}
		case generationjob.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case generationjob.FieldModality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field modality", values[i])
			} else if value.Valid {
				_m.Modality = value.String
			}
		case generationjob.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case generationjob.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case generationjob.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case generationjob.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case generationjob.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case generationjob.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case generationjob.FieldUpstreamGenerationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_generation_id", values[i])
			} else if value.Valid {
				_m.UpstreamGenerationID = new(string)
				*_m.UpstreamGenerationID = value.String
			}
		case generationjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = generationjob.Status(value.String)
			}
		case generationjob.FieldUpstreamStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_status", values[i])
			} else if value.Valid {
				_m.UpstreamStatus = new(string)
				*_m.UpstreamStatus = value.String
			}
		case generationjob.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				_m.RequestHash = value.String
			}
		case generationjob.FieldRequestPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestPayload); err != nil {
					return fmt.Errorf("unmarshal field request_payload: %w", err)
				}
			}
		case generationjob.FieldResultPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResultPayload); err != nil {
					return fmt.Errorf("unmarshal field result_payload: %w", err)
				}
			}
		case generationjob.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case generationjob.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case generationjob.FieldOutputCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_count", values[i])
			} else if value.Valid {
				_m.OutputCount = int(value.Int64)
			}
		case generationjob.FieldActualUpstreamCostAmount:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field actual_upstream_cost_amount", values[i])
			} else if value.Valid {
				_m.ActualUpstreamCostAmount = value.S.(*decimal.Decimal)
			}
		case generationjob.FieldActualUpstreamCostUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actual_upstream_cost_unit", values[i])
			} else if value.Valid {
				_m.ActualUpstreamCostUnit = new(string)
				*_m.ActualUpstreamCostUnit = value.String
			}
		case generationjob.FieldCustomerCost:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field customer_cost", values[i])
			} else if value.Valid {
				_m.CustomerCost = value.S.(*decimal.Decimal)
			}
		case generationjob.FieldBillingStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_status", values[i])
			} else if value.Valid {
				_m.BillingStatus = generationjob.BillingStatus(value.String)
			}
		case generationjob.FieldBillingReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_reference", values[i])
			} else if value.Valid {
				_m.BillingReference = new(string)
				*_m.BillingReference = value.String
			}
		case generationjob.FieldPollAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field poll_attempts", values[i])
			} else if value.Valid {
				_m.PollAttempts = int(value.Int64)
			}
		case generationjob.FieldNextPollAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_poll_at", values[i])
			} else if value.Valid {
				_m.NextPollAt = new(time.Time)
				*_m.NextPollAt = value.Time
			}
		case generationjob.FieldLastPolledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_polled_at", values[i])
			} else if value.Valid {
				_m.LastPolledAt = new(time.Time)
				*_m.LastPolledAt = value.Time
			}
		case generationjob.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = new(time.Time)
				*_m.SubmittedAt = value.Time
			}
		case generationjob.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case generationjob.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case generationjob.FieldFailedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field failed_at", values[i])
			} else if value.Valid {
				_m.FailedAt = new(time.Time)
				*_m.FailedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GenerationJob.
// This includes values selected through modifiers, order, etc.
func (_m *GenerationJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GenerationJob.
// Note that you need to call GenerationJob.Unwrap() before calling this method if this GenerationJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GenerationJob) Update() *GenerationJobUpdateOne {
	return NewGenerationJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GenerationJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GenerationJob) Unwrap() *GenerationJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GenerationJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GenerationJob) String() string {
	var builder strings.Builder
	builder.WriteString("GenerationJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("public_id=")
	builder.WriteString(_m.PublicID)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("modality=")
	builder.WriteString(_m.Modality)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	if v := _m.UpstreamGenerationID; v != nil {
		builder.WriteString("upstream_generation_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.UpstreamStatus; v != nil {
		builder.WriteString("upstream_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(_m.RequestHash)
	builder.WriteString(", ")
	builder.WriteString("request_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestPayload))
	builder.WriteString(", ")
	builder.WriteString("result_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultPayload))
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("output_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputCount))
	builder.WriteString(", ")
	if v := _m.ActualUpstreamCostAmount; v != nil {
		builder.WriteString("actual_upstream_cost_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ActualUpstreamCostUnit; v != nil {
		builder.WriteString("actual_upstream_cost_unit=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CustomerCost; v != nil {
		builder.WriteString("customer_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("billing_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillingStatus))
	builder.WriteString(", ")
	if v := _m.BillingReference; v != nil {
		builder.WriteString("billing_reference=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("poll_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.PollAttempts))
	builder.WriteString(", ")
	if v := _m.NextPollAt; v != nil {
		builder.WriteString("next_poll_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastPolledAt; v != nil {
		builder.WriteString("last_polled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SubmittedAt; v != nil {
		builder.WriteString("submitted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FailedAt; v != nil {
		builder.WriteString("failed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// GenerationJobs is a parsable slice of GenerationJob.
type GenerationJobs []*GenerationJob
