// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ideamessage"
)

// IdeaMessage is the model entity for the IdeaMessage schema.
type IdeaMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 留言作者用户ID
	AuthorID int64 `json:"author_id,omitempty"`
	// 作者名快照
	AuthorName string `json:"author_name,omitempty"`
	// 留言标题
	Title string `json:"title,omitempty"`
	// 留言正文
	Content string `json:"content,omitempty"`
	// 管理员单条官方回复
	AdminReply *string `json:"admin_reply,omitempty"`
	// 回复管理员用户ID
	AdminReplyBy *int64 `json:"admin_reply_by,omitempty"`
	// 管理员回复时间
	AdminReplyAt *time.Time `json:"admin_reply_at,omitempty"`
	// 状态: active, user_deleted, admin_deleted
	Status       string `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IdeaMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ideamessage.FieldID, ideamessage.FieldAuthorID, ideamessage.FieldAdminReplyBy:
			values[i] = new(sql.NullInt64)
		case ideamessage.FieldAuthorName, ideamessage.FieldTitle, ideamessage.FieldContent, ideamessage.FieldAdminReply, ideamessage.FieldStatus:
			values[i] = new(sql.NullString)
		case ideamessage.FieldCreatedAt, ideamessage.FieldUpdatedAt, ideamessage.FieldDeletedAt, ideamessage.FieldAdminReplyAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IdeaMessage fields.
func (_m *IdeaMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ideamessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ideamessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ideamessage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ideamessage.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case ideamessage.FieldAuthorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field author_id", values[i])
			} else if value.Valid {
				_m.AuthorID = value.Int64
			}
		case ideamessage.FieldAuthorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author_name", values[i])
			} else if value.Valid {
				_m.AuthorName = value.String
			}
		case ideamessage.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case ideamessage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case ideamessage.FieldAdminReply:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_reply", values[i])
			} else if value.Valid {
				_m.AdminReply = new(string)
				*_m.AdminReply = value.String
			}
		case ideamessage.FieldAdminReplyBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field admin_reply_by", values[i])
			} else if value.Valid {
				_m.AdminReplyBy = new(int64)
				*_m.AdminReplyBy = value.Int64
			}
		case ideamessage.FieldAdminReplyAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field admin_reply_at", values[i])
			} else if value.Valid {
				_m.AdminReplyAt = new(time.Time)
				*_m.AdminReplyAt = value.Time
			}
		case ideamessage.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IdeaMessage.
// This includes values selected through modifiers, order, etc.
func (_m *IdeaMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IdeaMessage.
// Note that you need to call IdeaMessage.Unwrap() before calling this method if this IdeaMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IdeaMessage) Update() *IdeaMessageUpdateOne {
	return NewIdeaMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IdeaMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IdeaMessage) Unwrap() *IdeaMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IdeaMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IdeaMessage) String() string {
	var builder strings.Builder
	builder.WriteString("IdeaMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("author_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthorID))
	builder.WriteString(", ")
	builder.WriteString("author_name=")
	builder.WriteString(_m.AuthorName)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	if v := _m.AdminReply; v != nil {
		builder.WriteString("admin_reply=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AdminReplyBy; v != nil {
		builder.WriteString("admin_reply_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AdminReplyAt; v != nil {
		builder.WriteString("admin_reply_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// IdeaMessages is a parsable slice of IdeaMessage.
type IdeaMessages []*IdeaMessage
