// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ideamessage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// IdeaMessageUpdate is the builder for updating IdeaMessage entities.
type IdeaMessageUpdate struct {
	config
	hooks    []Hook
	mutation *IdeaMessageMutation
}

// Where appends a list predicates to the IdeaMessageUpdate builder.
func (_u *IdeaMessageUpdate) Where(ps ...predicate.IdeaMessage) *IdeaMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IdeaMessageUpdate) SetUpdatedAt(v time.Time) *IdeaMessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *IdeaMessageUpdate) SetDeletedAt(v time.Time) *IdeaMessageUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *IdeaMessageUpdate) SetNillableDeletedAt(v *time.Time) *IdeaMessageUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *IdeaMessageUpdate) ClearDeletedAt() *IdeaMessageUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *IdeaMessageUpdate) SetAuthorID(v int64) *IdeaMessageUpdate {
	_u.mutation.ResetAuthorID()
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *IdeaMessageUpdate) SetNillableAuthorID(v *int64) *IdeaMessageUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// AddAuthorID adds value to the "author_id" field.
func (_u *IdeaMessageUpdate) AddAuthorID(v int64) *IdeaMessageUpdate {
	_u.mutation.AddAuthorID(v)
	return _u
}

// SetAuthorName sets the "author_name" field.
func (_u *IdeaMessageUpdate) SetAuthorName(v string) *IdeaMessageUpdate {
	_u.mutation.SetAuthorName(v)
	return _u
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_u *IdeaMessageUpdate) SetNillableAuthorName(v *string) *IdeaMessageUpdate {
	if v != nil {
		_u.SetAuthorName(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *IdeaMessageUpdate) SetTitle(v string) *IdeaMessageUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *IdeaMessageUpdate) SetNillableTitle(v *string) *IdeaMessageUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *IdeaMessageUpdate) SetContent(v string) *IdeaMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *IdeaMessageUpdate) SetNillableContent(v *string) *IdeaMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetAdminReply sets the "admin_reply" field.
func (_u *IdeaMessageUpdate) SetAdminReply(v string) *IdeaMessageUpdate {
	_u.mutation.SetAdminReply(v)
	return _u
}

// SetNillableAdminReply sets the "admin_reply" field if the given value is not nil.
func (_u *IdeaMessageUpdate) SetNillableAdminReply(v *string) *IdeaMessageUpdate {
	if v != nil {
		_u.SetAdminReply(*v)
	}
	return _u
}

// ClearAdminReply clears the value of the "admin_reply" field.
func (_u *IdeaMessageUpdate) ClearAdminReply() *IdeaMessageUpdate {
	_u.mutation.ClearAdminReply()
	return _u
}

// SetAdminReplyBy sets the "admin_reply_by" field.
func (_u *IdeaMessageUpdate) SetAdminReplyBy(v int64) *IdeaMessageUpdate {
	_u.mutation.ResetAdminReplyBy()
	_u.mutation.SetAdminReplyBy(v)
	return _u
}

// SetNillableAdminReplyBy sets the "admin_reply_by" field if the given value is not nil.
func (_u *IdeaMessageUpdate) SetNillableAdminReplyBy(v *int64) *IdeaMessageUpdate {
	if v != nil {
		_u.SetAdminReplyBy(*v)
	}
	return _u
}

// AddAdminReplyBy adds value to the "admin_reply_by" field.
func (_u *IdeaMessageUpdate) AddAdminReplyBy(v int64) *IdeaMessageUpdate {
	_u.mutation.AddAdminReplyBy(v)
	return _u
}

// ClearAdminReplyBy clears the value of the "admin_reply_by" field.
func (_u *IdeaMessageUpdate) ClearAdminReplyBy() *IdeaMessageUpdate {
	_u.mutation.ClearAdminReplyBy()
	return _u
}

// SetAdminReplyAt sets the "admin_reply_at" field.
func (_u *IdeaMessageUpdate) SetAdminReplyAt(v time.Time) *IdeaMessageUpdate {
	_u.mutation.SetAdminReplyAt(v)
	return _u
}

// SetNillableAdminReplyAt sets the "admin_reply_at" field if the given value is not nil.
func (_u *IdeaMessageUpdate) SetNillableAdminReplyAt(v *time.Time) *IdeaMessageUpdate {
	if v != nil {
		_u.SetAdminReplyAt(*v)
	}
	return _u
}

// ClearAdminReplyAt clears the value of the "admin_reply_at" field.
func (_u *IdeaMessageUpdate) ClearAdminReplyAt() *IdeaMessageUpdate {
	_u.mutation.ClearAdminReplyAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *IdeaMessageUpdate) SetStatus(v string) *IdeaMessageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IdeaMessageUpdate) SetNillableStatus(v *string) *IdeaMessageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the IdeaMessageMutation object of the builder.
func (_u *IdeaMessageUpdate) Mutation() *IdeaMessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IdeaMessageUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdeaMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IdeaMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdeaMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IdeaMessageUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if ideamessage.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ideamessage.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ideamessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *IdeaMessageUpdate) check() error {
	if v, ok := _u.mutation.AuthorID(); ok {
		if err := ideamessage.AuthorIDValidator(v); err != nil {
			return &ValidationError{Name: "author_id", err: fmt.Errorf(`ent: validator failed for field "IdeaMessage.author_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorName(); ok {
		if err := ideamessage.AuthorNameValidator(v); err != nil {
			return &ValidationError{Name: "author_name", err: fmt.Errorf(`ent: validator failed for field "IdeaMessage.author_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := ideamessage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "IdeaMessage.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := ideamessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "IdeaMessage.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ideamessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IdeaMessage.status": %w`, err)}
		}
	}
	return nil
}

func (_u *IdeaMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ideamessage.Table, ideamessage.Columns, sqlgraph.NewFieldSpec(ideamessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ideamessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(ideamessage.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(ideamessage.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(ideamessage.FieldAuthorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthorID(); ok {
		_spec.AddField(ideamessage.FieldAuthorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AuthorName(); ok {
		_spec.SetField(ideamessage.FieldAuthorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(ideamessage.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(ideamessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.AdminReply(); ok {
		_spec.SetField(ideamessage.FieldAdminReply, field.TypeString, value)
	}
	if _u.mutation.AdminReplyCleared() {
		_spec.ClearField(ideamessage.FieldAdminReply, field.TypeString)
	}
	if value, ok := _u.mutation.AdminReplyBy(); ok {
		_spec.SetField(ideamessage.FieldAdminReplyBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAdminReplyBy(); ok {
		_spec.AddField(ideamessage.FieldAdminReplyBy, field.TypeInt64, value)
	}
	if _u.mutation.AdminReplyByCleared() {
		_spec.ClearField(ideamessage.FieldAdminReplyBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.AdminReplyAt(); ok {
		_spec.SetField(ideamessage.FieldAdminReplyAt, field.TypeTime, value)
	}
	if _u.mutation.AdminReplyAtCleared() {
		_spec.ClearField(ideamessage.FieldAdminReplyAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ideamessage.FieldStatus, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ideamessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IdeaMessageUpdateOne is the builder for updating a single IdeaMessage entity.
type IdeaMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IdeaMessageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IdeaMessageUpdateOne) SetUpdatedAt(v time.Time) *IdeaMessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *IdeaMessageUpdateOne) SetDeletedAt(v time.Time) *IdeaMessageUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *IdeaMessageUpdateOne) SetNillableDeletedAt(v *time.Time) *IdeaMessageUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *IdeaMessageUpdateOne) ClearDeletedAt() *IdeaMessageUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *IdeaMessageUpdateOne) SetAuthorID(v int64) *IdeaMessageUpdateOne {
	_u.mutation.ResetAuthorID()
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *IdeaMessageUpdateOne) SetNillableAuthorID(v *int64) *IdeaMessageUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// AddAuthorID adds value to the "author_id" field.
func (_u *IdeaMessageUpdateOne) AddAuthorID(v int64) *IdeaMessageUpdateOne {
	_u.mutation.AddAuthorID(v)
	return _u
}

// SetAuthorName sets the "author_name" field.
func (_u *IdeaMessageUpdateOne) SetAuthorName(v string) *IdeaMessageUpdateOne {
	_u.mutation.SetAuthorName(v)
	return _u
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_u *IdeaMessageUpdateOne) SetNillableAuthorName(v *string) *IdeaMessageUpdateOne {
	if v != nil {
		_u.SetAuthorName(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *IdeaMessageUpdateOne) SetTitle(v string) *IdeaMessageUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *IdeaMessageUpdateOne) SetNillableTitle(v *string) *IdeaMessageUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *IdeaMessageUpdateOne) SetContent(v string) *IdeaMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *IdeaMessageUpdateOne) SetNillableContent(v *string) *IdeaMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetAdminReply sets the "admin_reply" field.
func (_u *IdeaMessageUpdateOne) SetAdminReply(v string) *IdeaMessageUpdateOne {
	_u.mutation.SetAdminReply(v)
	return _u
}

// SetNillableAdminReply sets the "admin_reply" field if the given value is not nil.
func (_u *IdeaMessageUpdateOne) SetNillableAdminReply(v *string) *IdeaMessageUpdateOne {
	if v != nil {
		_u.SetAdminReply(*v)
	}
	return _u
}

// ClearAdminReply clears the value of the "admin_reply" field.
func (_u *IdeaMessageUpdateOne) ClearAdminReply() *IdeaMessageUpdateOne {
	_u.mutation.ClearAdminReply()
	return _u
}

// SetAdminReplyBy sets the "admin_reply_by" field.
func (_u *IdeaMessageUpdateOne) SetAdminReplyBy(v int64) *IdeaMessageUpdateOne {
	_u.mutation.ResetAdminReplyBy()
	_u.mutation.SetAdminReplyBy(v)
	return _u
}

// SetNillableAdminReplyBy sets the "admin_reply_by" field if the given value is not nil.
func (_u *IdeaMessageUpdateOne) SetNillableAdminReplyBy(v *int64) *IdeaMessageUpdateOne {
	if v != nil {
		_u.SetAdminReplyBy(*v)
	}
	return _u
}

// AddAdminReplyBy adds value to the "admin_reply_by" field.
func (_u *IdeaMessageUpdateOne) AddAdminReplyBy(v int64) *IdeaMessageUpdateOne {
	_u.mutation.AddAdminReplyBy(v)
	return _u
}

// ClearAdminReplyBy clears the value of the "admin_reply_by" field.
func (_u *IdeaMessageUpdateOne) ClearAdminReplyBy() *IdeaMessageUpdateOne {
	_u.mutation.ClearAdminReplyBy()
	return _u
}

// SetAdminReplyAt sets the "admin_reply_at" field.
func (_u *IdeaMessageUpdateOne) SetAdminReplyAt(v time.Time) *IdeaMessageUpdateOne {
	_u.mutation.SetAdminReplyAt(v)
	return _u
}

// SetNillableAdminReplyAt sets the "admin_reply_at" field if the given value is not nil.
func (_u *IdeaMessageUpdateOne) SetNillableAdminReplyAt(v *time.Time) *IdeaMessageUpdateOne {
	if v != nil {
		_u.SetAdminReplyAt(*v)
	}
	return _u
}

// ClearAdminReplyAt clears the value of the "admin_reply_at" field.
func (_u *IdeaMessageUpdateOne) ClearAdminReplyAt() *IdeaMessageUpdateOne {
	_u.mutation.ClearAdminReplyAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *IdeaMessageUpdateOne) SetStatus(v string) *IdeaMessageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IdeaMessageUpdateOne) SetNillableStatus(v *string) *IdeaMessageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the IdeaMessageMutation object of the builder.
func (_u *IdeaMessageUpdateOne) Mutation() *IdeaMessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the IdeaMessageUpdate builder.
func (_u *IdeaMessageUpdateOne) Where(ps ...predicate.IdeaMessage) *IdeaMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IdeaMessageUpdateOne) Select(field string, fields ...string) *IdeaMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IdeaMessage entity.
func (_u *IdeaMessageUpdateOne) Save(ctx context.Context) (*IdeaMessage, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdeaMessageUpdateOne) SaveX(ctx context.Context) *IdeaMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IdeaMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdeaMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IdeaMessageUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if ideamessage.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ideamessage.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ideamessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *IdeaMessageUpdateOne) check() error {
	if v, ok := _u.mutation.AuthorID(); ok {
		if err := ideamessage.AuthorIDValidator(v); err != nil {
			return &ValidationError{Name: "author_id", err: fmt.Errorf(`ent: validator failed for field "IdeaMessage.author_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorName(); ok {
		if err := ideamessage.AuthorNameValidator(v); err != nil {
			return &ValidationError{Name: "author_name", err: fmt.Errorf(`ent: validator failed for field "IdeaMessage.author_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := ideamessage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "IdeaMessage.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := ideamessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "IdeaMessage.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ideamessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IdeaMessage.status": %w`, err)}
		}
	}
	return nil
}

func (_u *IdeaMessageUpdateOne) sqlSave(ctx context.Context) (_node *IdeaMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ideamessage.Table, ideamessage.Columns, sqlgraph.NewFieldSpec(ideamessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IdeaMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ideamessage.FieldID)
		for _, f := range fields {
			if !ideamessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ideamessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ideamessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(ideamessage.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(ideamessage.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(ideamessage.FieldAuthorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthorID(); ok {
		_spec.AddField(ideamessage.FieldAuthorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AuthorName(); ok {
		_spec.SetField(ideamessage.FieldAuthorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(ideamessage.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(ideamessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.AdminReply(); ok {
		_spec.SetField(ideamessage.FieldAdminReply, field.TypeString, value)
	}
	if _u.mutation.AdminReplyCleared() {
		_spec.ClearField(ideamessage.FieldAdminReply, field.TypeString)
	}
	if value, ok := _u.mutation.AdminReplyBy(); ok {
		_spec.SetField(ideamessage.FieldAdminReplyBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAdminReplyBy(); ok {
		_spec.AddField(ideamessage.FieldAdminReplyBy, field.TypeInt64, value)
	}
	if _u.mutation.AdminReplyByCleared() {
		_spec.ClearField(ideamessage.FieldAdminReplyBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.AdminReplyAt(); ok {
		_spec.SetField(ideamessage.FieldAdminReplyAt, field.TypeTime, value)
	}
	if _u.mutation.AdminReplyAtCleared() {
		_spec.ClearField(ideamessage.FieldAdminReplyAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ideamessage.FieldStatus, field.TypeString, value)
	}
	_node = &IdeaMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ideamessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
