// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediaproduct"
	"github.com/Wei-Shaw/sub2api/ent/mediaproductprice"
	"github.com/shopspring/decimal"
)

// MediaProductPriceCreate is the builder for creating a MediaProductPrice entity.
type MediaProductPriceCreate struct {
	config
	mutation *MediaProductPriceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaProductPriceCreate) SetCreatedAt(v time.Time) *MediaProductPriceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MediaProductPriceCreate) SetNillableCreatedAt(v *time.Time) *MediaProductPriceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MediaProductPriceCreate) SetUpdatedAt(v time.Time) *MediaProductPriceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MediaProductPriceCreate) SetNillableUpdatedAt(v *time.Time) *MediaProductPriceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *MediaProductPriceCreate) SetProductID(v int64) *MediaProductPriceCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetOperation sets the "operation" field.
func (_c *MediaProductPriceCreate) SetOperation(v string) *MediaProductPriceCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetSpecKey sets the "spec_key" field.
func (_c *MediaProductPriceCreate) SetSpecKey(v string) *MediaProductPriceCreate {
	_c.mutation.SetSpecKey(v)
	return _c
}

// SetUnitPriceUsd sets the "unit_price_usd" field.
func (_c *MediaProductPriceCreate) SetUnitPriceUsd(v *decimal.Decimal) *MediaProductPriceCreate {
	_c.mutation.SetUnitPriceUsd(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *MediaProductPriceCreate) SetCurrency(v string) *MediaProductPriceCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *MediaProductPriceCreate) SetNillableCurrency(v *string) *MediaProductPriceCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *MediaProductPriceCreate) SetVersion(v string) *MediaProductPriceCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *MediaProductPriceCreate) SetEnabled(v bool) *MediaProductPriceCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *MediaProductPriceCreate) SetNillableEnabled(v *bool) *MediaProductPriceCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetProduct sets the "product" edge to the MediaProduct entity.
func (_c *MediaProductPriceCreate) SetProduct(v *MediaProduct) *MediaProductPriceCreate {
	return _c.SetProductID(v.ID)
}

// Mutation returns the MediaProductPriceMutation object of the builder.
func (_c *MediaProductPriceCreate) Mutation() *MediaProductPriceMutation {
	return _c.mutation
}

// Save creates the MediaProductPrice in the database.
func (_c *MediaProductPriceCreate) Save(ctx context.Context) (*MediaProductPrice, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaProductPriceCreate) SaveX(ctx context.Context) *MediaProductPrice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaProductPriceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaProductPriceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaProductPriceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mediaproductprice.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mediaproductprice.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := mediaproductprice.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := mediaproductprice.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaProductPriceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MediaProductPrice.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MediaProductPrice.updated_at"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "MediaProductPrice.product_id"`)}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "MediaProductPrice.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := mediaproductprice.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "MediaProductPrice.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SpecKey(); !ok {
		return &ValidationError{Name: "spec_key", err: errors.New(`ent: missing required field "MediaProductPrice.spec_key"`)}
	}
	if v, ok := _c.mutation.SpecKey(); ok {
		if err := mediaproductprice.SpecKeyValidator(v); err != nil {
			return &ValidationError{Name: "spec_key", err: fmt.Errorf(`ent: validator failed for field "MediaProductPrice.spec_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UnitPriceUsd(); !ok {
		return &ValidationError{Name: "unit_price_usd", err: errors.New(`ent: missing required field "MediaProductPrice.unit_price_usd"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "MediaProductPrice.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := mediaproductprice.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "MediaProductPrice.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "MediaProductPrice.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := mediaproductprice.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "MediaProductPrice.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "MediaProductPrice.enabled"`)}
	}
	if len(_c.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "MediaProductPrice.product"`)}
	}
	return nil
}

func (_c *MediaProductPriceCreate) sqlSave(ctx context.Context) (*MediaProductPrice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaProductPriceCreate) createSpec() (*MediaProductPrice, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaProductPrice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediaproductprice.Table, sqlgraph.NewFieldSpec(mediaproductprice.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mediaproductprice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mediaproductprice.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(mediaproductprice.FieldOperation, field.TypeString, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.SpecKey(); ok {
		_spec.SetField(mediaproductprice.FieldSpecKey, field.TypeString, value)
		_node.SpecKey = value
	}
	if value, ok := _c.mutation.UnitPriceUsd(); ok {
		_spec.SetField(mediaproductprice.FieldUnitPriceUsd, field.TypeOther, value)
		_node.UnitPriceUsd = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(mediaproductprice.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(mediaproductprice.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(mediaproductprice.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaproductprice.ProductTable,
			Columns: []string{mediaproductprice.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MediaProductPrice.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MediaProductPriceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MediaProductPriceCreate) OnConflict(opts ...sql.ConflictOption) *MediaProductPriceUpsertOne {
	_c.conflict = opts
	return &MediaProductPriceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MediaProductPrice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MediaProductPriceCreate) OnConflictColumns(columns ...string) *MediaProductPriceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MediaProductPriceUpsertOne{
		create: _c,
	}
}

type (
	// MediaProductPriceUpsertOne is the builder for "upsert"-ing
	//  one MediaProductPrice node.
	MediaProductPriceUpsertOne struct {
		create *MediaProductPriceCreate
	}

	// MediaProductPriceUpsert is the "OnConflict" setter.
	MediaProductPriceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaProductPriceUpsert) SetUpdatedAt(v time.Time) *MediaProductPriceUpsert {
	u.Set(mediaproductprice.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaProductPriceUpsert) UpdateUpdatedAt() *MediaProductPriceUpsert {
	u.SetExcluded(mediaproductprice.FieldUpdatedAt)
	return u
}

// SetProductID sets the "product_id" field.
func (u *MediaProductPriceUpsert) SetProductID(v int64) *MediaProductPriceUpsert {
	u.Set(mediaproductprice.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *MediaProductPriceUpsert) UpdateProductID() *MediaProductPriceUpsert {
	u.SetExcluded(mediaproductprice.FieldProductID)
	return u
}

// SetOperation sets the "operation" field.
func (u *MediaProductPriceUpsert) SetOperation(v string) *MediaProductPriceUpsert {
	u.Set(mediaproductprice.FieldOperation, v)
	return u
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *MediaProductPriceUpsert) UpdateOperation() *MediaProductPriceUpsert {
	u.SetExcluded(mediaproductprice.FieldOperation)
	return u
}

// SetSpecKey sets the "spec_key" field.
func (u *MediaProductPriceUpsert) SetSpecKey(v string) *MediaProductPriceUpsert {
	u.Set(mediaproductprice.FieldSpecKey, v)
	return u
}

// UpdateSpecKey sets the "spec_key" field to the value that was provided on create.
func (u *MediaProductPriceUpsert) UpdateSpecKey() *MediaProductPriceUpsert {
	u.SetExcluded(mediaproductprice.FieldSpecKey)
	return u
}

// SetUnitPriceUsd sets the "unit_price_usd" field.
func (u *MediaProductPriceUpsert) SetUnitPriceUsd(v *decimal.Decimal) *MediaProductPriceUpsert {
	u.Set(mediaproductprice.FieldUnitPriceUsd, v)
	return u
}

// UpdateUnitPriceUsd sets the "unit_price_usd" field to the value that was provided on create.
func (u *MediaProductPriceUpsert) UpdateUnitPriceUsd() *MediaProductPriceUpsert {
	u.SetExcluded(mediaproductprice.FieldUnitPriceUsd)
	return u
}

// SetCurrency sets the "currency" field.
func (u *MediaProductPriceUpsert) SetCurrency(v string) *MediaProductPriceUpsert {
	u.Set(mediaproductprice.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *MediaProductPriceUpsert) UpdateCurrency() *MediaProductPriceUpsert {
	u.SetExcluded(mediaproductprice.FieldCurrency)
	return u
}

// SetVersion sets the "version" field.
func (u *MediaProductPriceUpsert) SetVersion(v string) *MediaProductPriceUpsert {
	u.Set(mediaproductprice.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *MediaProductPriceUpsert) UpdateVersion() *MediaProductPriceUpsert {
	u.SetExcluded(mediaproductprice.FieldVersion)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *MediaProductPriceUpsert) SetEnabled(v bool) *MediaProductPriceUpsert {
	u.Set(mediaproductprice.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *MediaProductPriceUpsert) UpdateEnabled() *MediaProductPriceUpsert {
	u.SetExcluded(mediaproductprice.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MediaProductPrice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MediaProductPriceUpsertOne) UpdateNewValues() *MediaProductPriceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(mediaproductprice.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MediaProductPrice.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MediaProductPriceUpsertOne) Ignore() *MediaProductPriceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MediaProductPriceUpsertOne) DoNothing() *MediaProductPriceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MediaProductPriceCreate.OnConflict
// documentation for more info.
func (u *MediaProductPriceUpsertOne) Update(set func(*MediaProductPriceUpsert)) *MediaProductPriceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MediaProductPriceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaProductPriceUpsertOne) SetUpdatedAt(v time.Time) *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaProductPriceUpsertOne) UpdateUpdatedAt() *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProductID sets the "product_id" field.
func (u *MediaProductPriceUpsertOne) SetProductID(v int64) *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *MediaProductPriceUpsertOne) UpdateProductID() *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateProductID()
	})
}

// SetOperation sets the "operation" field.
func (u *MediaProductPriceUpsertOne) SetOperation(v string) *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *MediaProductPriceUpsertOne) UpdateOperation() *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateOperation()
	})
}

// SetSpecKey sets the "spec_key" field.
func (u *MediaProductPriceUpsertOne) SetSpecKey(v string) *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetSpecKey(v)
	})
}

// UpdateSpecKey sets the "spec_key" field to the value that was provided on create.
func (u *MediaProductPriceUpsertOne) UpdateSpecKey() *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateSpecKey()
	})
}

// SetUnitPriceUsd sets the "unit_price_usd" field.
func (u *MediaProductPriceUpsertOne) SetUnitPriceUsd(v *decimal.Decimal) *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetUnitPriceUsd(v)
	})
}

// UpdateUnitPriceUsd sets the "unit_price_usd" field to the value that was provided on create.
func (u *MediaProductPriceUpsertOne) UpdateUnitPriceUsd() *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateUnitPriceUsd()
	})
}

// SetCurrency sets the "currency" field.
func (u *MediaProductPriceUpsertOne) SetCurrency(v string) *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *MediaProductPriceUpsertOne) UpdateCurrency() *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateCurrency()
	})
}

// SetVersion sets the "version" field.
func (u *MediaProductPriceUpsertOne) SetVersion(v string) *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *MediaProductPriceUpsertOne) UpdateVersion() *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateVersion()
	})
}

// SetEnabled sets the "enabled" field.
func (u *MediaProductPriceUpsertOne) SetEnabled(v bool) *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *MediaProductPriceUpsertOne) UpdateEnabled() *MediaProductPriceUpsertOne {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *MediaProductPriceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MediaProductPriceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MediaProductPriceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MediaProductPriceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MediaProductPriceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MediaProductPriceCreateBulk is the builder for creating many MediaProductPrice entities in bulk.
type MediaProductPriceCreateBulk struct {
	config
	err      error
	builders []*MediaProductPriceCreate
	conflict []sql.ConflictOption
}

// Save creates the MediaProductPrice entities in the database.
func (_c *MediaProductPriceCreateBulk) Save(ctx context.Context) ([]*MediaProductPrice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaProductPrice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaProductPriceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaProductPriceCreateBulk) SaveX(ctx context.Context) []*MediaProductPrice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaProductPriceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaProductPriceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MediaProductPrice.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MediaProductPriceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MediaProductPriceCreateBulk) OnConflict(opts ...sql.ConflictOption) *MediaProductPriceUpsertBulk {
	_c.conflict = opts
	return &MediaProductPriceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MediaProductPrice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MediaProductPriceCreateBulk) OnConflictColumns(columns ...string) *MediaProductPriceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MediaProductPriceUpsertBulk{
		create: _c,
	}
}

// MediaProductPriceUpsertBulk is the builder for "upsert"-ing
// a bulk of MediaProductPrice nodes.
type MediaProductPriceUpsertBulk struct {
	create *MediaProductPriceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MediaProductPrice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MediaProductPriceUpsertBulk) UpdateNewValues() *MediaProductPriceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(mediaproductprice.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MediaProductPrice.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MediaProductPriceUpsertBulk) Ignore() *MediaProductPriceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MediaProductPriceUpsertBulk) DoNothing() *MediaProductPriceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MediaProductPriceCreateBulk.OnConflict
// documentation for more info.
func (u *MediaProductPriceUpsertBulk) Update(set func(*MediaProductPriceUpsert)) *MediaProductPriceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MediaProductPriceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaProductPriceUpsertBulk) SetUpdatedAt(v time.Time) *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaProductPriceUpsertBulk) UpdateUpdatedAt() *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProductID sets the "product_id" field.
func (u *MediaProductPriceUpsertBulk) SetProductID(v int64) *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *MediaProductPriceUpsertBulk) UpdateProductID() *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateProductID()
	})
}

// SetOperation sets the "operation" field.
func (u *MediaProductPriceUpsertBulk) SetOperation(v string) *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *MediaProductPriceUpsertBulk) UpdateOperation() *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateOperation()
	})
}

// SetSpecKey sets the "spec_key" field.
func (u *MediaProductPriceUpsertBulk) SetSpecKey(v string) *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetSpecKey(v)
	})
}

// UpdateSpecKey sets the "spec_key" field to the value that was provided on create.
func (u *MediaProductPriceUpsertBulk) UpdateSpecKey() *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateSpecKey()
	})
}

// SetUnitPriceUsd sets the "unit_price_usd" field.
func (u *MediaProductPriceUpsertBulk) SetUnitPriceUsd(v *decimal.Decimal) *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetUnitPriceUsd(v)
	})
}

// UpdateUnitPriceUsd sets the "unit_price_usd" field to the value that was provided on create.
func (u *MediaProductPriceUpsertBulk) UpdateUnitPriceUsd() *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateUnitPriceUsd()
	})
}

// SetCurrency sets the "currency" field.
func (u *MediaProductPriceUpsertBulk) SetCurrency(v string) *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *MediaProductPriceUpsertBulk) UpdateCurrency() *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateCurrency()
	})
}

// SetVersion sets the "version" field.
func (u *MediaProductPriceUpsertBulk) SetVersion(v string) *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *MediaProductPriceUpsertBulk) UpdateVersion() *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateVersion()
	})
}

// SetEnabled sets the "enabled" field.
func (u *MediaProductPriceUpsertBulk) SetEnabled(v bool) *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *MediaProductPriceUpsertBulk) UpdateEnabled() *MediaProductPriceUpsertBulk {
	return u.Update(func(s *MediaProductPriceUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *MediaProductPriceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MediaProductPriceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MediaProductPriceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MediaProductPriceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
