// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediaproduct"
	"github.com/Wei-Shaw/sub2api/ent/mediaproductprice"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/shopspring/decimal"
)

// MediaProductPriceUpdate is the builder for updating MediaProductPrice entities.
type MediaProductPriceUpdate struct {
	config
	hooks    []Hook
	mutation *MediaProductPriceMutation
}

// Where appends a list predicates to the MediaProductPriceUpdate builder.
func (_u *MediaProductPriceUpdate) Where(ps ...predicate.MediaProductPrice) *MediaProductPriceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaProductPriceUpdate) SetUpdatedAt(v time.Time) *MediaProductPriceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *MediaProductPriceUpdate) SetProductID(v int64) *MediaProductPriceUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *MediaProductPriceUpdate) SetNillableProductID(v *int64) *MediaProductPriceUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *MediaProductPriceUpdate) SetOperation(v string) *MediaProductPriceUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *MediaProductPriceUpdate) SetNillableOperation(v *string) *MediaProductPriceUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetSpecKey sets the "spec_key" field.
func (_u *MediaProductPriceUpdate) SetSpecKey(v string) *MediaProductPriceUpdate {
	_u.mutation.SetSpecKey(v)
	return _u
}

// SetNillableSpecKey sets the "spec_key" field if the given value is not nil.
func (_u *MediaProductPriceUpdate) SetNillableSpecKey(v *string) *MediaProductPriceUpdate {
	if v != nil {
		_u.SetSpecKey(*v)
	}
	return _u
}

// SetUnitPriceUsd sets the "unit_price_usd" field.
func (_u *MediaProductPriceUpdate) SetUnitPriceUsd(v *decimal.Decimal) *MediaProductPriceUpdate {
	_u.mutation.SetUnitPriceUsd(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *MediaProductPriceUpdate) SetCurrency(v string) *MediaProductPriceUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *MediaProductPriceUpdate) SetNillableCurrency(v *string) *MediaProductPriceUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *MediaProductPriceUpdate) SetVersion(v string) *MediaProductPriceUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *MediaProductPriceUpdate) SetNillableVersion(v *string) *MediaProductPriceUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *MediaProductPriceUpdate) SetEnabled(v bool) *MediaProductPriceUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *MediaProductPriceUpdate) SetNillableEnabled(v *bool) *MediaProductPriceUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetProduct sets the "product" edge to the MediaProduct entity.
func (_u *MediaProductPriceUpdate) SetProduct(v *MediaProduct) *MediaProductPriceUpdate {
	return _u.SetProductID(v.ID)
}

// Mutation returns the MediaProductPriceMutation object of the builder.
func (_u *MediaProductPriceUpdate) Mutation() *MediaProductPriceMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the MediaProduct entity.
func (_u *MediaProductPriceUpdate) ClearProduct() *MediaProductPriceUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaProductPriceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaProductPriceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaProductPriceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaProductPriceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaProductPriceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediaproductprice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaProductPriceUpdate) check() error {
	if v, ok := _u.mutation.Operation(); ok {
		if err := mediaproductprice.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "MediaProductPrice.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpecKey(); ok {
		if err := mediaproductprice.SpecKeyValidator(v); err != nil {
			return &ValidationError{Name: "spec_key", err: fmt.Errorf(`ent: validator failed for field "MediaProductPrice.spec_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := mediaproductprice.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "MediaProductPrice.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := mediaproductprice.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "MediaProductPrice.version": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaProductPrice.product"`)
	}
	return nil
}

func (_u *MediaProductPriceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaproductprice.Table, mediaproductprice.Columns, sqlgraph.NewFieldSpec(mediaproductprice.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediaproductprice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(mediaproductprice.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecKey(); ok {
		_spec.SetField(mediaproductprice.FieldSpecKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnitPriceUsd(); ok {
		_spec.SetField(mediaproductprice.FieldUnitPriceUsd, field.TypeOther, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(mediaproductprice.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(mediaproductprice.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(mediaproductprice.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaproductprice.ProductTable,
			Columns: []string{mediaproductprice.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaproduct.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaproductprice.ProductTable,
			Columns: []string{mediaproductprice.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaproductprice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaProductPriceUpdateOne is the builder for updating a single MediaProductPrice entity.
type MediaProductPriceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaProductPriceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaProductPriceUpdateOne) SetUpdatedAt(v time.Time) *MediaProductPriceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *MediaProductPriceUpdateOne) SetProductID(v int64) *MediaProductPriceUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *MediaProductPriceUpdateOne) SetNillableProductID(v *int64) *MediaProductPriceUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *MediaProductPriceUpdateOne) SetOperation(v string) *MediaProductPriceUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *MediaProductPriceUpdateOne) SetNillableOperation(v *string) *MediaProductPriceUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetSpecKey sets the "spec_key" field.
func (_u *MediaProductPriceUpdateOne) SetSpecKey(v string) *MediaProductPriceUpdateOne {
	_u.mutation.SetSpecKey(v)
	return _u
}

// SetNillableSpecKey sets the "spec_key" field if the given value is not nil.
func (_u *MediaProductPriceUpdateOne) SetNillableSpecKey(v *string) *MediaProductPriceUpdateOne {
	if v != nil {
		_u.SetSpecKey(*v)
	}
	return _u
}

// SetUnitPriceUsd sets the "unit_price_usd" field.
func (_u *MediaProductPriceUpdateOne) SetUnitPriceUsd(v *decimal.Decimal) *MediaProductPriceUpdateOne {
	_u.mutation.SetUnitPriceUsd(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *MediaProductPriceUpdateOne) SetCurrency(v string) *MediaProductPriceUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *MediaProductPriceUpdateOne) SetNillableCurrency(v *string) *MediaProductPriceUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *MediaProductPriceUpdateOne) SetVersion(v string) *MediaProductPriceUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *MediaProductPriceUpdateOne) SetNillableVersion(v *string) *MediaProductPriceUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *MediaProductPriceUpdateOne) SetEnabled(v bool) *MediaProductPriceUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *MediaProductPriceUpdateOne) SetNillableEnabled(v *bool) *MediaProductPriceUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetProduct sets the "product" edge to the MediaProduct entity.
func (_u *MediaProductPriceUpdateOne) SetProduct(v *MediaProduct) *MediaProductPriceUpdateOne {
	return _u.SetProductID(v.ID)
}

// Mutation returns the MediaProductPriceMutation object of the builder.
func (_u *MediaProductPriceUpdateOne) Mutation() *MediaProductPriceMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the MediaProduct entity.
func (_u *MediaProductPriceUpdateOne) ClearProduct() *MediaProductPriceUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// Where appends a list predicates to the MediaProductPriceUpdate builder.
func (_u *MediaProductPriceUpdateOne) Where(ps ...predicate.MediaProductPrice) *MediaProductPriceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaProductPriceUpdateOne) Select(field string, fields ...string) *MediaProductPriceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaProductPrice entity.
func (_u *MediaProductPriceUpdateOne) Save(ctx context.Context) (*MediaProductPrice, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaProductPriceUpdateOne) SaveX(ctx context.Context) *MediaProductPrice {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaProductPriceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaProductPriceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaProductPriceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediaproductprice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaProductPriceUpdateOne) check() error {
	if v, ok := _u.mutation.Operation(); ok {
		if err := mediaproductprice.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "MediaProductPrice.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpecKey(); ok {
		if err := mediaproductprice.SpecKeyValidator(v); err != nil {
			return &ValidationError{Name: "spec_key", err: fmt.Errorf(`ent: validator failed for field "MediaProductPrice.spec_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := mediaproductprice.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "MediaProductPrice.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := mediaproductprice.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "MediaProductPrice.version": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaProductPrice.product"`)
	}
	return nil
}

func (_u *MediaProductPriceUpdateOne) sqlSave(ctx context.Context) (_node *MediaProductPrice, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaproductprice.Table, mediaproductprice.Columns, sqlgraph.NewFieldSpec(mediaproductprice.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaProductPrice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaproductprice.FieldID)
		for _, f := range fields {
			if !mediaproductprice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediaproductprice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediaproductprice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(mediaproductprice.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecKey(); ok {
		_spec.SetField(mediaproductprice.FieldSpecKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnitPriceUsd(); ok {
		_spec.SetField(mediaproductprice.FieldUnitPriceUsd, field.TypeOther, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(mediaproductprice.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(mediaproductprice.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(mediaproductprice.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaproductprice.ProductTable,
			Columns: []string{mediaproductprice.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaproduct.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaproductprice.ProductTable,
			Columns: []string{mediaproductprice.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MediaProductPrice{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaproductprice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
