// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/mediaoffer"
	"github.com/Wei-Shaw/sub2api/ent/mediaproduct"
	"github.com/Wei-Shaw/sub2api/ent/mediaproductprice"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MediaProductUpdate is the builder for updating MediaProduct entities.
type MediaProductUpdate struct {
	config
	hooks    []Hook
	mutation *MediaProductMutation
}

// Where appends a list predicates to the MediaProductUpdate builder.
func (_u *MediaProductUpdate) Where(ps ...predicate.MediaProduct) *MediaProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaProductUpdate) SetUpdatedAt(v time.Time) *MediaProductUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublicModel sets the "public_model" field.
func (_u *MediaProductUpdate) SetPublicModel(v string) *MediaProductUpdate {
	_u.mutation.SetPublicModel(v)
	return _u
}

// SetNillablePublicModel sets the "public_model" field if the given value is not nil.
func (_u *MediaProductUpdate) SetNillablePublicModel(v *string) *MediaProductUpdate {
	if v != nil {
		_u.SetPublicModel(*v)
	}
	return _u
}

// SetModality sets the "modality" field.
func (_u *MediaProductUpdate) SetModality(v mediaproduct.Modality) *MediaProductUpdate {
	_u.mutation.SetModality(v)
	return _u
}

// SetNillableModality sets the "modality" field if the given value is not nil.
func (_u *MediaProductUpdate) SetNillableModality(v *mediaproduct.Modality) *MediaProductUpdate {
	if v != nil {
		_u.SetModality(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *MediaProductUpdate) SetEnabled(v bool) *MediaProductUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *MediaProductUpdate) SetNillableEnabled(v *bool) *MediaProductUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MediaProductUpdate) SetDescription(v string) *MediaProductUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MediaProductUpdate) SetNillableDescription(v *string) *MediaProductUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MediaProductUpdate) ClearDescription() *MediaProductUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// AddPriceIDs adds the "prices" edge to the MediaProductPrice entity by IDs.
func (_u *MediaProductUpdate) AddPriceIDs(ids ...int64) *MediaProductUpdate {
	_u.mutation.AddPriceIDs(ids...)
	return _u
}

// AddPrices adds the "prices" edges to the MediaProductPrice entity.
func (_u *MediaProductUpdate) AddPrices(v ...*MediaProductPrice) *MediaProductUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPriceIDs(ids...)
}

// AddOfferIDs adds the "offers" edge to the MediaOffer entity by IDs.
func (_u *MediaProductUpdate) AddOfferIDs(ids ...int64) *MediaProductUpdate {
	_u.mutation.AddOfferIDs(ids...)
	return _u
}

// AddOffers adds the "offers" edges to the MediaOffer entity.
func (_u *MediaProductUpdate) AddOffers(v ...*MediaOffer) *MediaProductUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOfferIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *MediaProductUpdate) AddGroupIDs(ids ...int64) *MediaProductUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *MediaProductUpdate) AddGroups(v ...*Group) *MediaProductUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// Mutation returns the MediaProductMutation object of the builder.
func (_u *MediaProductUpdate) Mutation() *MediaProductMutation {
	return _u.mutation
}

// ClearPrices clears all "prices" edges to the MediaProductPrice entity.
func (_u *MediaProductUpdate) ClearPrices() *MediaProductUpdate {
	_u.mutation.ClearPrices()
	return _u
}

// RemovePriceIDs removes the "prices" edge to MediaProductPrice entities by IDs.
func (_u *MediaProductUpdate) RemovePriceIDs(ids ...int64) *MediaProductUpdate {
	_u.mutation.RemovePriceIDs(ids...)
	return _u
}

// RemovePrices removes "prices" edges to MediaProductPrice entities.
func (_u *MediaProductUpdate) RemovePrices(v ...*MediaProductPrice) *MediaProductUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePriceIDs(ids...)
}

// ClearOffers clears all "offers" edges to the MediaOffer entity.
func (_u *MediaProductUpdate) ClearOffers() *MediaProductUpdate {
	_u.mutation.ClearOffers()
	return _u
}

// RemoveOfferIDs removes the "offers" edge to MediaOffer entities by IDs.
func (_u *MediaProductUpdate) RemoveOfferIDs(ids ...int64) *MediaProductUpdate {
	_u.mutation.RemoveOfferIDs(ids...)
	return _u
}

// RemoveOffers removes "offers" edges to MediaOffer entities.
func (_u *MediaProductUpdate) RemoveOffers(v ...*MediaOffer) *MediaProductUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOfferIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *MediaProductUpdate) ClearGroups() *MediaProductUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *MediaProductUpdate) RemoveGroupIDs(ids ...int64) *MediaProductUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *MediaProductUpdate) RemoveGroups(v ...*Group) *MediaProductUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaProductUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaProductUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediaproduct.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaProductUpdate) check() error {
	if v, ok := _u.mutation.PublicModel(); ok {
		if err := mediaproduct.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "MediaProduct.public_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Modality(); ok {
		if err := mediaproduct.ModalityValidator(v); err != nil {
			return &ValidationError{Name: "modality", err: fmt.Errorf(`ent: validator failed for field "MediaProduct.modality": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaproduct.Table, mediaproduct.Columns, sqlgraph.NewFieldSpec(mediaproduct.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediaproduct.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicModel(); ok {
		_spec.SetField(mediaproduct.FieldPublicModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Modality(); ok {
		_spec.SetField(mediaproduct.FieldModality, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(mediaproduct.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(mediaproduct.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(mediaproduct.FieldDescription, field.TypeString)
	}
	if _u.mutation.PricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaproduct.PricesTable,
			Columns: []string{mediaproduct.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaproductprice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPricesIDs(); len(nodes) > 0 && !_u.mutation.PricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaproduct.PricesTable,
			Columns: []string{mediaproduct.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaproductprice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PricesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaproduct.PricesTable,
			Columns: []string{mediaproduct.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaproductprice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OffersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaproduct.OffersTable,
			Columns: []string{mediaproduct.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaoffer.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOffersIDs(); len(nodes) > 0 && !_u.mutation.OffersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaproduct.OffersTable,
			Columns: []string{mediaproduct.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaoffer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OffersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaproduct.OffersTable,
			Columns: []string{mediaproduct.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaoffer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   mediaproduct.GroupsTable,
			Columns: mediaproduct.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   mediaproduct.GroupsTable,
			Columns: mediaproduct.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   mediaproduct.GroupsTable,
			Columns: mediaproduct.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaProductUpdateOne is the builder for updating a single MediaProduct entity.
type MediaProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaProductMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaProductUpdateOne) SetUpdatedAt(v time.Time) *MediaProductUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublicModel sets the "public_model" field.
func (_u *MediaProductUpdateOne) SetPublicModel(v string) *MediaProductUpdateOne {
	_u.mutation.SetPublicModel(v)
	return _u
}

// SetNillablePublicModel sets the "public_model" field if the given value is not nil.
func (_u *MediaProductUpdateOne) SetNillablePublicModel(v *string) *MediaProductUpdateOne {
	if v != nil {
		_u.SetPublicModel(*v)
	}
	return _u
}

// SetModality sets the "modality" field.
func (_u *MediaProductUpdateOne) SetModality(v mediaproduct.Modality) *MediaProductUpdateOne {
	_u.mutation.SetModality(v)
	return _u
}

// SetNillableModality sets the "modality" field if the given value is not nil.
func (_u *MediaProductUpdateOne) SetNillableModality(v *mediaproduct.Modality) *MediaProductUpdateOne {
	if v != nil {
		_u.SetModality(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *MediaProductUpdateOne) SetEnabled(v bool) *MediaProductUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *MediaProductUpdateOne) SetNillableEnabled(v *bool) *MediaProductUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MediaProductUpdateOne) SetDescription(v string) *MediaProductUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MediaProductUpdateOne) SetNillableDescription(v *string) *MediaProductUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MediaProductUpdateOne) ClearDescription() *MediaProductUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// AddPriceIDs adds the "prices" edge to the MediaProductPrice entity by IDs.
func (_u *MediaProductUpdateOne) AddPriceIDs(ids ...int64) *MediaProductUpdateOne {
	_u.mutation.AddPriceIDs(ids...)
	return _u
}

// AddPrices adds the "prices" edges to the MediaProductPrice entity.
func (_u *MediaProductUpdateOne) AddPrices(v ...*MediaProductPrice) *MediaProductUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPriceIDs(ids...)
}

// AddOfferIDs adds the "offers" edge to the MediaOffer entity by IDs.
func (_u *MediaProductUpdateOne) AddOfferIDs(ids ...int64) *MediaProductUpdateOne {
	_u.mutation.AddOfferIDs(ids...)
	return _u
}

// AddOffers adds the "offers" edges to the MediaOffer entity.
func (_u *MediaProductUpdateOne) AddOffers(v ...*MediaOffer) *MediaProductUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOfferIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *MediaProductUpdateOne) AddGroupIDs(ids ...int64) *MediaProductUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *MediaProductUpdateOne) AddGroups(v ...*Group) *MediaProductUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// Mutation returns the MediaProductMutation object of the builder.
func (_u *MediaProductUpdateOne) Mutation() *MediaProductMutation {
	return _u.mutation
}

// ClearPrices clears all "prices" edges to the MediaProductPrice entity.
func (_u *MediaProductUpdateOne) ClearPrices() *MediaProductUpdateOne {
	_u.mutation.ClearPrices()
	return _u
}

// RemovePriceIDs removes the "prices" edge to MediaProductPrice entities by IDs.
func (_u *MediaProductUpdateOne) RemovePriceIDs(ids ...int64) *MediaProductUpdateOne {
	_u.mutation.RemovePriceIDs(ids...)
	return _u
}

// RemovePrices removes "prices" edges to MediaProductPrice entities.
func (_u *MediaProductUpdateOne) RemovePrices(v ...*MediaProductPrice) *MediaProductUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePriceIDs(ids...)
}

// ClearOffers clears all "offers" edges to the MediaOffer entity.
func (_u *MediaProductUpdateOne) ClearOffers() *MediaProductUpdateOne {
	_u.mutation.ClearOffers()
	return _u
}

// RemoveOfferIDs removes the "offers" edge to MediaOffer entities by IDs.
func (_u *MediaProductUpdateOne) RemoveOfferIDs(ids ...int64) *MediaProductUpdateOne {
	_u.mutation.RemoveOfferIDs(ids...)
	return _u
}

// RemoveOffers removes "offers" edges to MediaOffer entities.
func (_u *MediaProductUpdateOne) RemoveOffers(v ...*MediaOffer) *MediaProductUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOfferIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *MediaProductUpdateOne) ClearGroups() *MediaProductUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *MediaProductUpdateOne) RemoveGroupIDs(ids ...int64) *MediaProductUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *MediaProductUpdateOne) RemoveGroups(v ...*Group) *MediaProductUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// Where appends a list predicates to the MediaProductUpdate builder.
func (_u *MediaProductUpdateOne) Where(ps ...predicate.MediaProduct) *MediaProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaProductUpdateOne) Select(field string, fields ...string) *MediaProductUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaProduct entity.
func (_u *MediaProductUpdateOne) Save(ctx context.Context) (*MediaProduct, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaProductUpdateOne) SaveX(ctx context.Context) *MediaProduct {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaProductUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediaproduct.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaProductUpdateOne) check() error {
	if v, ok := _u.mutation.PublicModel(); ok {
		if err := mediaproduct.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "MediaProduct.public_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Modality(); ok {
		if err := mediaproduct.ModalityValidator(v); err != nil {
			return &ValidationError{Name: "modality", err: fmt.Errorf(`ent: validator failed for field "MediaProduct.modality": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaProductUpdateOne) sqlSave(ctx context.Context) (_node *MediaProduct, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaproduct.Table, mediaproduct.Columns, sqlgraph.NewFieldSpec(mediaproduct.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaProduct.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaproduct.FieldID)
		for _, f := range fields {
			if !mediaproduct.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediaproduct.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediaproduct.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicModel(); ok {
		_spec.SetField(mediaproduct.FieldPublicModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Modality(); ok {
		_spec.SetField(mediaproduct.FieldModality, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(mediaproduct.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(mediaproduct.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(mediaproduct.FieldDescription, field.TypeString)
	}
	if _u.mutation.PricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaproduct.PricesTable,
			Columns: []string{mediaproduct.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaproductprice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPricesIDs(); len(nodes) > 0 && !_u.mutation.PricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaproduct.PricesTable,
			Columns: []string{mediaproduct.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaproductprice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PricesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaproduct.PricesTable,
			Columns: []string{mediaproduct.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaproductprice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OffersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaproduct.OffersTable,
			Columns: []string{mediaproduct.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaoffer.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOffersIDs(); len(nodes) > 0 && !_u.mutation.OffersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaproduct.OffersTable,
			Columns: []string{mediaproduct.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaoffer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OffersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaproduct.OffersTable,
			Columns: []string{mediaproduct.OffersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaoffer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   mediaproduct.GroupsTable,
			Columns: mediaproduct.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   mediaproduct.GroupsTable,
			Columns: mediaproduct.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   mediaproduct.GroupsTable,
			Columns: mediaproduct.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MediaProduct{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
