// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/mediaproduct"
	"github.com/Wei-Shaw/sub2api/ent/mediaproductprice"
	"github.com/shopspring/decimal"
)

// MediaProductPrice is the model entity for the MediaProductPrice schema.
type MediaProductPrice struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID int64 `json:"product_id,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation string `json:"operation,omitempty"`
	// SpecKey holds the value of the "spec_key" field.
	SpecKey string `json:"spec_key,omitempty"`
	// UnitPriceUsd holds the value of the "unit_price_usd" field.
	UnitPriceUsd *decimal.Decimal `json:"unit_price_usd,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MediaProductPriceQuery when eager-loading is set.
	Edges        MediaProductPriceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MediaProductPriceEdges holds the relations/edges for other nodes in the graph.
type MediaProductPriceEdges struct {
	// Product holds the value of the product edge.
	Product *MediaProduct `json:"product,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaProductPriceEdges) ProductOrErr() (*MediaProduct, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: mediaproduct.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MediaProductPrice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mediaproductprice.FieldUnitPriceUsd:
			values[i] = new(decimal.Decimal)
		case mediaproductprice.FieldEnabled:
			values[i] = new(sql.NullBool)
		case mediaproductprice.FieldID, mediaproductprice.FieldProductID:
			values[i] = new(sql.NullInt64)
		case mediaproductprice.FieldOperation, mediaproductprice.FieldSpecKey, mediaproductprice.FieldCurrency, mediaproductprice.FieldVersion:
			values[i] = new(sql.NullString)
		case mediaproductprice.FieldCreatedAt, mediaproductprice.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MediaProductPrice fields.
func (_m *MediaProductPrice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mediaproductprice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case mediaproductprice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mediaproductprice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case mediaproductprice.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = value.Int64
			}
		case mediaproductprice.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = value.String
			}
		case mediaproductprice.FieldSpecKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spec_key", values[i])
			} else if value.Valid {
				_m.SpecKey = value.String
			}
		case mediaproductprice.FieldUnitPriceUsd:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field unit_price_usd", values[i])
			} else if value != nil {
				_m.UnitPriceUsd = value
			}
		case mediaproductprice.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case mediaproductprice.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case mediaproductprice.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MediaProductPrice.
// This includes values selected through modifiers, order, etc.
func (_m *MediaProductPrice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProduct queries the "product" edge of the MediaProductPrice entity.
func (_m *MediaProductPrice) QueryProduct() *MediaProductQuery {
	return NewMediaProductPriceClient(_m.config).QueryProduct(_m)
}

// Update returns a builder for updating this MediaProductPrice.
// Note that you need to call MediaProductPrice.Unwrap() before calling this method if this MediaProductPrice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MediaProductPrice) Update() *MediaProductPriceUpdateOne {
	return NewMediaProductPriceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MediaProductPrice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MediaProductPrice) Unwrap() *MediaProductPrice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MediaProductPrice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MediaProductPrice) String() string {
	var builder strings.Builder
	builder.WriteString("MediaProductPrice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductID))
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(_m.Operation)
	builder.WriteString(", ")
	builder.WriteString("spec_key=")
	builder.WriteString(_m.SpecKey)
	builder.WriteString(", ")
	builder.WriteString("unit_price_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnitPriceUsd))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// MediaProductPrices is a parsable slice of MediaProductPrice.
type MediaProductPrices []*MediaProductPrice
