// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/mediaproduct"
)

// MediaProduct is the model entity for the MediaProduct schema.
type MediaProduct struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PublicModel holds the value of the "public_model" field.
	PublicModel string `json:"public_model,omitempty"`
	// Modality holds the value of the "modality" field.
	Modality mediaproduct.Modality `json:"modality,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MediaProductQuery when eager-loading is set.
	Edges        MediaProductEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MediaProductEdges holds the relations/edges for other nodes in the graph.
type MediaProductEdges struct {
	// Prices holds the value of the prices edge.
	Prices []*MediaProductPrice `json:"prices,omitempty"`
	// Offers holds the value of the offers edge.
	Offers []*MediaOffer `json:"offers,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*Group `json:"groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PricesOrErr returns the Prices value or an error if the edge
// was not loaded in eager-loading.
func (e MediaProductEdges) PricesOrErr() ([]*MediaProductPrice, error) {
	if e.loadedTypes[0] {
		return e.Prices, nil
	}
	return nil, &NotLoadedError{edge: "prices"}
}

// OffersOrErr returns the Offers value or an error if the edge
// was not loaded in eager-loading.
func (e MediaProductEdges) OffersOrErr() ([]*MediaOffer, error) {
	if e.loadedTypes[1] {
		return e.Offers, nil
	}
	return nil, &NotLoadedError{edge: "offers"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e MediaProductEdges) GroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[2] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MediaProduct) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mediaproduct.FieldEnabled:
			values[i] = new(sql.NullBool)
		case mediaproduct.FieldID:
			values[i] = new(sql.NullInt64)
		case mediaproduct.FieldPublicModel, mediaproduct.FieldModality, mediaproduct.FieldDescription:
			values[i] = new(sql.NullString)
		case mediaproduct.FieldCreatedAt, mediaproduct.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MediaProduct fields.
func (_m *MediaProduct) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mediaproduct.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case mediaproduct.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mediaproduct.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case mediaproduct.FieldPublicModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_model", values[i])
			} else if value.Valid {
				_m.PublicModel = value.String
			}
		case mediaproduct.FieldModality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field modality", values[i])
			} else if value.Valid {
				_m.Modality = mediaproduct.Modality(value.String)
			}
		case mediaproduct.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case mediaproduct.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MediaProduct.
// This includes values selected through modifiers, order, etc.
func (_m *MediaProduct) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPrices queries the "prices" edge of the MediaProduct entity.
func (_m *MediaProduct) QueryPrices() *MediaProductPriceQuery {
	return NewMediaProductClient(_m.config).QueryPrices(_m)
}

// QueryOffers queries the "offers" edge of the MediaProduct entity.
func (_m *MediaProduct) QueryOffers() *MediaOfferQuery {
	return NewMediaProductClient(_m.config).QueryOffers(_m)
}

// QueryGroups queries the "groups" edge of the MediaProduct entity.
func (_m *MediaProduct) QueryGroups() *GroupQuery {
	return NewMediaProductClient(_m.config).QueryGroups(_m)
}

// Update returns a builder for updating this MediaProduct.
// Note that you need to call MediaProduct.Unwrap() before calling this method if this MediaProduct
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MediaProduct) Update() *MediaProductUpdateOne {
	return NewMediaProductClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MediaProduct entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MediaProduct) Unwrap() *MediaProduct {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MediaProduct is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MediaProduct) String() string {
	var builder strings.Builder
	builder.WriteString("MediaProduct(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("public_model=")
	builder.WriteString(_m.PublicModel)
	builder.WriteString(", ")
	builder.WriteString("modality=")
	builder.WriteString(fmt.Sprintf("%v", _m.Modality))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// MediaProducts is a parsable slice of MediaProduct.
type MediaProducts []*MediaProduct
