// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediaproductprice"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MediaProductPriceDelete is the builder for deleting a MediaProductPrice entity.
type MediaProductPriceDelete struct {
	config
	hooks    []Hook
	mutation *MediaProductPriceMutation
}

// Where appends a list predicates to the MediaProductPriceDelete builder.
func (_d *MediaProductPriceDelete) Where(ps ...predicate.MediaProductPrice) *MediaProductPriceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MediaProductPriceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MediaProductPriceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MediaProductPriceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mediaproductprice.Table, sqlgraph.NewFieldSpec(mediaproductprice.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MediaProductPriceDeleteOne is the builder for deleting a single MediaProductPrice entity.
type MediaProductPriceDeleteOne struct {
	_d *MediaProductPriceDelete
}

// Where appends a list predicates to the MediaProductPriceDelete builder.
func (_d *MediaProductPriceDeleteOne) Where(ps ...predicate.MediaProductPrice) *MediaProductPriceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MediaProductPriceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mediaproductprice.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MediaProductPriceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
