// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/mediaoffer"
	"github.com/Wei-Shaw/sub2api/ent/mediaproduct"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MediaOfferQuery is the builder for querying MediaOffer entities.
type MediaOfferQuery struct {
	config
	ctx             *QueryContext
	order           []mediaoffer.OrderOption
	inters          []Interceptor
	predicates      []predicate.MediaOffer
	withProduct     *MediaProductQuery
	withSourceGroup *GroupQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MediaOfferQuery builder.
func (_q *MediaOfferQuery) Where(ps ...predicate.MediaOffer) *MediaOfferQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MediaOfferQuery) Limit(limit int) *MediaOfferQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MediaOfferQuery) Offset(offset int) *MediaOfferQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MediaOfferQuery) Unique(unique bool) *MediaOfferQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MediaOfferQuery) Order(o ...mediaoffer.OrderOption) *MediaOfferQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProduct chains the current query on the "product" edge.
func (_q *MediaOfferQuery) QueryProduct() *MediaProductQuery {
	query := (&MediaProductClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mediaoffer.Table, mediaoffer.FieldID, selector),
			sqlgraph.To(mediaproduct.Table, mediaproduct.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mediaoffer.ProductTable, mediaoffer.ProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySourceGroup chains the current query on the "source_group" edge.
func (_q *MediaOfferQuery) QuerySourceGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mediaoffer.Table, mediaoffer.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mediaoffer.SourceGroupTable, mediaoffer.SourceGroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MediaOffer entity from the query.
// Returns a *NotFoundError when no MediaOffer was found.
func (_q *MediaOfferQuery) First(ctx context.Context) (*MediaOffer, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mediaoffer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MediaOfferQuery) FirstX(ctx context.Context) *MediaOffer {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MediaOffer ID from the query.
// Returns a *NotFoundError when no MediaOffer ID was found.
func (_q *MediaOfferQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mediaoffer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MediaOfferQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MediaOffer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MediaOffer entity is found.
// Returns a *NotFoundError when no MediaOffer entities are found.
func (_q *MediaOfferQuery) Only(ctx context.Context) (*MediaOffer, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mediaoffer.Label}
	default:
		return nil, &NotSingularError{mediaoffer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MediaOfferQuery) OnlyX(ctx context.Context) *MediaOffer {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MediaOffer ID in the query.
// Returns a *NotSingularError when more than one MediaOffer ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MediaOfferQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mediaoffer.Label}
	default:
		err = &NotSingularError{mediaoffer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MediaOfferQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MediaOffers.
func (_q *MediaOfferQuery) All(ctx context.Context) ([]*MediaOffer, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MediaOffer, *MediaOfferQuery]()
	return withInterceptors[[]*MediaOffer](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MediaOfferQuery) AllX(ctx context.Context) []*MediaOffer {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MediaOffer IDs.
func (_q *MediaOfferQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(mediaoffer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MediaOfferQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MediaOfferQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MediaOfferQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MediaOfferQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MediaOfferQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MediaOfferQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MediaOfferQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MediaOfferQuery) Clone() *MediaOfferQuery {
	if _q == nil {
		return nil
	}
	return &MediaOfferQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]mediaoffer.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.MediaOffer{}, _q.predicates...),
		withProduct:     _q.withProduct.Clone(),
		withSourceGroup: _q.withSourceGroup.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProduct tells the query-builder to eager-load the nodes that are connected to
// the "product" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MediaOfferQuery) WithProduct(opts ...func(*MediaProductQuery)) *MediaOfferQuery {
	query := (&MediaProductClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProduct = query
	return _q
}

// WithSourceGroup tells the query-builder to eager-load the nodes that are connected to
// the "source_group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MediaOfferQuery) WithSourceGroup(opts ...func(*GroupQuery)) *MediaOfferQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSourceGroup = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MediaOffer.Query().
//		GroupBy(mediaoffer.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MediaOfferQuery) GroupBy(field string, fields ...string) *MediaOfferGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MediaOfferGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = mediaoffer.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.MediaOffer.Query().
//		Select(mediaoffer.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *MediaOfferQuery) Select(fields ...string) *MediaOfferSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MediaOfferSelect{MediaOfferQuery: _q}
	sbuild.label = mediaoffer.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MediaOfferSelect configured with the given aggregations.
func (_q *MediaOfferQuery) Aggregate(fns ...AggregateFunc) *MediaOfferSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MediaOfferQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !mediaoffer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MediaOfferQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MediaOffer, error) {
	var (
		nodes       = []*MediaOffer{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withProduct != nil,
			_q.withSourceGroup != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MediaOffer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MediaOffer{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProduct; query != nil {
		if err := _q.loadProduct(ctx, query, nodes, nil,
			func(n *MediaOffer, e *MediaProduct) { n.Edges.Product = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSourceGroup; query != nil {
		if err := _q.loadSourceGroup(ctx, query, nodes, nil,
			func(n *MediaOffer, e *Group) { n.Edges.SourceGroup = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MediaOfferQuery) loadProduct(ctx context.Context, query *MediaProductQuery, nodes []*MediaOffer, init func(*MediaOffer), assign func(*MediaOffer, *MediaProduct)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*MediaOffer)
	for i := range nodes {
		fk := nodes[i].ProductID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(mediaproduct.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "product_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *MediaOfferQuery) loadSourceGroup(ctx context.Context, query *GroupQuery, nodes []*MediaOffer, init func(*MediaOffer), assign func(*MediaOffer, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*MediaOffer)
	for i := range nodes {
		fk := nodes[i].SourceGroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "source_group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *MediaOfferQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MediaOfferQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mediaoffer.Table, mediaoffer.Columns, sqlgraph.NewFieldSpec(mediaoffer.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaoffer.FieldID)
		for i := range fields {
			if fields[i] != mediaoffer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProduct != nil {
			_spec.Node.AddColumnOnce(mediaoffer.FieldProductID)
		}
		if _q.withSourceGroup != nil {
			_spec.Node.AddColumnOnce(mediaoffer.FieldSourceGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MediaOfferQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(mediaoffer.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = mediaoffer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *MediaOfferQuery) ForUpdate(opts ...sql.LockOption) *MediaOfferQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *MediaOfferQuery) ForShare(opts ...sql.LockOption) *MediaOfferQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// MediaOfferGroupBy is the group-by builder for MediaOffer entities.
type MediaOfferGroupBy struct {
	selector
	build *MediaOfferQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MediaOfferGroupBy) Aggregate(fns ...AggregateFunc) *MediaOfferGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MediaOfferGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MediaOfferQuery, *MediaOfferGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MediaOfferGroupBy) sqlScan(ctx context.Context, root *MediaOfferQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MediaOfferSelect is the builder for selecting fields of MediaOffer entities.
type MediaOfferSelect struct {
	*MediaOfferQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MediaOfferSelect) Aggregate(fns ...AggregateFunc) *MediaOfferSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MediaOfferSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MediaOfferQuery, *MediaOfferSelect](ctx, _s.MediaOfferQuery, _s, _s.inters, v)
}

func (_s *MediaOfferSelect) sqlScan(ctx context.Context, root *MediaOfferQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
