// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// UsageLog is the model entity for the UsageLog schema.
type UsageLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// RequestedModel holds the value of the "requested_model" field.
	RequestedModel *string `json:"requested_model,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel *string `json:"upstream_model,omitempty"`
	// 渠道 ID
	ChannelID *int64 `json:"channel_id,omitempty"`
	// 模型映射链
	ModelMappingChain *string `json:"model_mapping_chain,omitempty"`
	// 计费层级标签
	BillingTier *string `json:"billing_tier,omitempty"`
	// 计费模式：token/per_request/image
	BillingMode *string `json:"billing_mode,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// MediaProductID holds the value of the "media_product_id" field.
	MediaProductID *int64 `json:"media_product_id,omitempty"`
	// MediaOfferID holds the value of the "media_offer_id" field.
	MediaOfferID *int64 `json:"media_offer_id,omitempty"`
	// UpstreamPlatform holds the value of the "upstream_platform" field.
	UpstreamPlatform *string `json:"upstream_platform,omitempty"`
	// SourceGroupID holds the value of the "source_group_id" field.
	SourceGroupID *int64 `json:"source_group_id,omitempty"`
	// TrustedCostAmount holds the value of the "trusted_cost_amount" field.
	TrustedCostAmount *float64 `json:"trusted_cost_amount,omitempty"`
	// TrustedCostUnit holds the value of the "trusted_cost_unit" field.
	TrustedCostUnit *string `json:"trusted_cost_unit,omitempty"`
	// TrustedCostSource holds the value of the "trusted_cost_source" field.
	TrustedCostSource *string `json:"trusted_cost_source,omitempty"`
	// TrustedCostVersion holds the value of the "trusted_cost_version" field.
	TrustedCostVersion *string `json:"trusted_cost_version,omitempty"`
	// CustomerPriceVersion holds the value of the "customer_price_version" field.
	CustomerPriceVersion *string `json:"customer_price_version,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID *int64 `json:"subscription_id,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int `json:"output_tokens,omitempty"`
	// CacheCreationTokens holds the value of the "cache_creation_tokens" field.
	CacheCreationTokens int `json:"cache_creation_tokens,omitempty"`
	// CacheReadTokens holds the value of the "cache_read_tokens" field.
	CacheReadTokens int `json:"cache_read_tokens,omitempty"`
	// CacheCreation5mTokens holds the value of the "cache_creation_5m_tokens" field.
	CacheCreation5mTokens int `json:"cache_creation_5m_tokens,omitempty"`
	// CacheCreation1hTokens holds the value of the "cache_creation_1h_tokens" field.
	CacheCreation1hTokens int `json:"cache_creation_1h_tokens,omitempty"`
	// InputCost holds the value of the "input_cost" field.
	InputCost float64 `json:"input_cost,omitempty"`
	// OutputCost holds the value of the "output_cost" field.
	OutputCost float64 `json:"output_cost,omitempty"`
	// CacheCreationCost holds the value of the "cache_creation_cost" field.
	CacheCreationCost float64 `json:"cache_creation_cost,omitempty"`
	// CacheReadCost holds the value of the "cache_read_cost" field.
	CacheReadCost float64 `json:"cache_read_cost,omitempty"`
	// TotalCost holds the value of the "total_cost" field.
	TotalCost float64 `json:"total_cost,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost float64 `json:"actual_cost,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// AccountRateMultiplier holds the value of the "account_rate_multiplier" field.
	AccountRateMultiplier *float64 `json:"account_rate_multiplier,omitempty"`
	// BillingType holds the value of the "billing_type" field.
	BillingType int8 `json:"billing_type,omitempty"`
	// Stream holds the value of the "stream" field.
	Stream bool `json:"stream,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs *int `json:"duration_ms,omitempty"`
	// FirstTokenMs holds the value of the "first_token_ms" field.
	FirstTokenMs *int `json:"first_token_ms,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent *string `json:"user_agent,omitempty"`
	// IPAddress holds the value of the "ip_address" field.
	IPAddress *string `json:"ip_address,omitempty"`
	// ImageCount holds the value of the "image_count" field.
	ImageCount int `json:"image_count,omitempty"`
	// ImageSize holds the value of the "image_size" field.
	ImageSize *string `json:"image_size,omitempty"`
	// ImageInputSize holds the value of the "image_input_size" field.
	ImageInputSize *string `json:"image_input_size,omitempty"`
	// ImageOutputSize holds the value of the "image_output_size" field.
	ImageOutputSize *string `json:"image_output_size,omitempty"`
	// ImageSizeSource holds the value of the "image_size_source" field.
	ImageSizeSource *string `json:"image_size_source,omitempty"`
	// ImageSizeBreakdown holds the value of the "image_size_breakdown" field.
	ImageSizeBreakdown map[string]int `json:"image_size_breakdown,omitempty"`
	// SearchCount holds the value of the "search_count" field.
	SearchCount int `json:"search_count,omitempty"`
	// AudioMode holds the value of the "audio_mode" field.
	AudioMode *string `json:"audio_mode,omitempty"`
	// AudioUnits holds the value of the "audio_units" field.
	AudioUnits *float64 `json:"audio_units,omitempty"`
	// CacheTTLOverridden holds the value of the "cache_ttl_overridden" field.
	CacheTTLOverridden bool `json:"cache_ttl_overridden,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageLogQuery when eager-loading is set.
	Edges        UsageLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsageLogEdges holds the relations/edges for other nodes in the graph.
type UsageLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagelog.FieldImageSizeBreakdown:
			values[i] = new([]byte)
		case usagelog.FieldStream, usagelog.FieldCacheTTLOverridden:
			values[i] = new(sql.NullBool)
		case usagelog.FieldTrustedCostAmount, usagelog.FieldInputCost, usagelog.FieldOutputCost, usagelog.FieldCacheCreationCost, usagelog.FieldCacheReadCost, usagelog.FieldTotalCost, usagelog.FieldActualCost, usagelog.FieldRateMultiplier, usagelog.FieldAccountRateMultiplier, usagelog.FieldAudioUnits:
			values[i] = new(sql.NullFloat64)
		case usagelog.FieldID, usagelog.FieldUserID, usagelog.FieldAPIKeyID, usagelog.FieldAccountID, usagelog.FieldChannelID, usagelog.FieldGroupID, usagelog.FieldMediaProductID, usagelog.FieldMediaOfferID, usagelog.FieldSourceGroupID, usagelog.FieldSubscriptionID, usagelog.FieldInputTokens, usagelog.FieldOutputTokens, usagelog.FieldCacheCreationTokens, usagelog.FieldCacheReadTokens, usagelog.FieldCacheCreation5mTokens, usagelog.FieldCacheCreation1hTokens, usagelog.FieldBillingType, usagelog.FieldDurationMs, usagelog.FieldFirstTokenMs, usagelog.FieldImageCount, usagelog.FieldSearchCount:
			values[i] = new(sql.NullInt64)
		case usagelog.FieldRequestID, usagelog.FieldModel, usagelog.FieldRequestedModel, usagelog.FieldUpstreamModel, usagelog.FieldModelMappingChain, usagelog.FieldBillingTier, usagelog.FieldBillingMode, usagelog.FieldUpstreamPlatform, usagelog.FieldTrustedCostUnit, usagelog.FieldTrustedCostSource, usagelog.FieldTrustedCostVersion, usagelog.FieldCustomerPriceVersion, usagelog.FieldUserAgent, usagelog.FieldIPAddress, usagelog.FieldImageSize, usagelog.FieldImageInputSize, usagelog.FieldImageOutputSize, usagelog.FieldImageSizeSource, usagelog.FieldAudioMode:
			values[i] = new(sql.NullString)
		case usagelog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageLog fields.
func (_m *UsageLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagelog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usagelog.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case usagelog.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case usagelog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case usagelog.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case usagelog.FieldRequestedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_model", values[i])
			} else if value.Valid {
				_m.RequestedModel = new(string)
				*_m.RequestedModel = value.String
			}
		case usagelog.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = new(string)
				*_m.UpstreamModel = value.String
			}
		case usagelog.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = new(int64)
				*_m.ChannelID = value.Int64
			}
		case usagelog.FieldModelMappingChain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_mapping_chain", values[i])
			} else if value.Valid {
				_m.ModelMappingChain = new(string)
				*_m.ModelMappingChain = value.String
			}
		case usagelog.FieldBillingTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_tier", values[i])
			} else if value.Valid {
				_m.BillingTier = new(string)
				*_m.BillingTier = value.String
			}
		case usagelog.FieldBillingMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_mode", values[i])
			} else if value.Valid {
				_m.BillingMode = new(string)
				*_m.BillingMode = value.String
			}
		case usagelog.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case usagelog.FieldMediaProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field media_product_id", values[i])
			} else if value.Valid {
				_m.MediaProductID = new(int64)
				*_m.MediaProductID = value.Int64
			}
		case usagelog.FieldMediaOfferID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field media_offer_id", values[i])
			} else if value.Valid {
				_m.MediaOfferID = new(int64)
				*_m.MediaOfferID = value.Int64
			}
		case usagelog.FieldUpstreamPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_platform", values[i])
			} else if value.Valid {
				_m.UpstreamPlatform = new(string)
				*_m.UpstreamPlatform = value.String
			}
		case usagelog.FieldSourceGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_group_id", values[i])
			} else if value.Valid {
				_m.SourceGroupID = new(int64)
				*_m.SourceGroupID = value.Int64
			}
		case usagelog.FieldTrustedCostAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field trusted_cost_amount", values[i])
			} else if value.Valid {
				_m.TrustedCostAmount = new(float64)
				*_m.TrustedCostAmount = value.Float64
			}
		case usagelog.FieldTrustedCostUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trusted_cost_unit", values[i])
			} else if value.Valid {
				_m.TrustedCostUnit = new(string)
				*_m.TrustedCostUnit = value.String
			}
		case usagelog.FieldTrustedCostSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trusted_cost_source", values[i])
			} else if value.Valid {
				_m.TrustedCostSource = new(string)
				*_m.TrustedCostSource = value.String
			}
		case usagelog.FieldTrustedCostVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trusted_cost_version", values[i])
			} else if value.Valid {
				_m.TrustedCostVersion = new(string)
				*_m.TrustedCostVersion = value.String
			}
		case usagelog.FieldCustomerPriceVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_price_version", values[i])
			} else if value.Valid {
				_m.CustomerPriceVersion = new(string)
				*_m.CustomerPriceVersion = value.String
			}
		case usagelog.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = new(int64)
				*_m.SubscriptionID = value.Int64
			}
		case usagelog.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = int(value.Int64)
			}
		case usagelog.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = int(value.Int64)
			}
		case usagelog.FieldCacheCreationTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreationTokens = int(value.Int64)
			}
		case usagelog.FieldCacheReadTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_tokens", values[i])
			} else if value.Valid {
				_m.CacheReadTokens = int(value.Int64)
			}
		case usagelog.FieldCacheCreation5mTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_5m_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreation5mTokens = int(value.Int64)
			}
		case usagelog.FieldCacheCreation1hTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_1h_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreation1hTokens = int(value.Int64)
			}
		case usagelog.FieldInputCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_cost", values[i])
			} else if value.Valid {
				_m.InputCost = value.Float64
			}
		case usagelog.FieldOutputCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_cost", values[i])
			} else if value.Valid {
				_m.OutputCost = value.Float64
			}
		case usagelog.FieldCacheCreationCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_cost", values[i])
			} else if value.Valid {
				_m.CacheCreationCost = value.Float64
			}
		case usagelog.FieldCacheReadCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_cost", values[i])
			} else if value.Valid {
				_m.CacheReadCost = value.Float64
			}
		case usagelog.FieldTotalCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_cost", values[i])
			} else if value.Valid {
				_m.TotalCost = value.Float64
			}
		case usagelog.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = value.Float64
			}
		case usagelog.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = value.Float64
			}
		case usagelog.FieldAccountRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field account_rate_multiplier", values[i])
			} else if value.Valid {
				_m.AccountRateMultiplier = new(float64)
				*_m.AccountRateMultiplier = value.Float64
			}
		case usagelog.FieldBillingType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field billing_type", values[i])
			} else if value.Valid {
				_m.BillingType = int8(value.Int64)
			}
		case usagelog.FieldStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream", values[i])
			} else if value.Valid {
				_m.Stream = value.Bool
			}
		case usagelog.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = new(int)
				*_m.DurationMs = int(value.Int64)
			}
		case usagelog.FieldFirstTokenMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field first_token_ms", values[i])
			} else if value.Valid {
				_m.FirstTokenMs = new(int)
				*_m.FirstTokenMs = int(value.Int64)
			}
		case usagelog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = new(string)
				*_m.UserAgent = value.String
			}
		case usagelog.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				_m.IPAddress = new(string)
				*_m.IPAddress = value.String
			}
		case usagelog.FieldImageCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field image_count", values[i])
			} else if value.Valid {
				_m.ImageCount = int(value.Int64)
			}
		case usagelog.FieldImageSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_size", values[i])
			} else if value.Valid {
				_m.ImageSize = new(string)
				*_m.ImageSize = value.String
			}
		case usagelog.FieldImageInputSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_input_size", values[i])
			} else if value.Valid {
				_m.ImageInputSize = new(string)
				*_m.ImageInputSize = value.String
			}
		case usagelog.FieldImageOutputSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_output_size", values[i])
			} else if value.Valid {
				_m.ImageOutputSize = new(string)
				*_m.ImageOutputSize = value.String
			}
		case usagelog.FieldImageSizeSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_size_source", values[i])
			} else if value.Valid {
				_m.ImageSizeSource = new(string)
				*_m.ImageSizeSource = value.String
			}
		case usagelog.FieldImageSizeBreakdown:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field image_size_breakdown", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ImageSizeBreakdown); err != nil {
					return fmt.Errorf("unmarshal field image_size_breakdown: %w", err)
				}
			}
		case usagelog.FieldSearchCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field search_count", values[i])
			} else if value.Valid {
				_m.SearchCount = int(value.Int64)
			}
		case usagelog.FieldAudioMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field audio_mode", values[i])
			} else if value.Valid {
				_m.AudioMode = new(string)
				*_m.AudioMode = value.String
			}
		case usagelog.FieldAudioUnits:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field audio_units", values[i])
			} else if value.Valid {
				_m.AudioUnits = new(float64)
				*_m.AudioUnits = value.Float64
			}
		case usagelog.FieldCacheTTLOverridden:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field cache_ttl_overridden", values[i])
			} else if value.Valid {
				_m.CacheTTLOverridden = value.Bool
			}
		case usagelog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageLog.
// This includes values selected through modifiers, order, etc.
func (_m *UsageLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UsageLog entity.
func (_m *UsageLog) QueryUser() *UserQuery {
	return NewUsageLogClient(_m.config).QueryUser(_m)
}

// QueryAPIKey queries the "api_key" edge of the UsageLog entity.
func (_m *UsageLog) QueryAPIKey() *APIKeyQuery {
	return NewUsageLogClient(_m.config).QueryAPIKey(_m)
}

// QueryAccount queries the "account" edge of the UsageLog entity.
func (_m *UsageLog) QueryAccount() *AccountQuery {
	return NewUsageLogClient(_m.config).QueryAccount(_m)
}

// QueryGroup queries the "group" edge of the UsageLog entity.
func (_m *UsageLog) QueryGroup() *GroupQuery {
	return NewUsageLogClient(_m.config).QueryGroup(_m)
}

// QuerySubscription queries the "subscription" edge of the UsageLog entity.
func (_m *UsageLog) QuerySubscription() *UserSubscriptionQuery {
	return NewUsageLogClient(_m.config).QuerySubscription(_m)
}

// Update returns a builder for updating this UsageLog.
// Note that you need to call UsageLog.Unwrap() before calling this method if this UsageLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageLog) Update() *UsageLogUpdateOne {
	return NewUsageLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageLog) Unwrap() *UsageLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageLog) String() string {
	var builder strings.Builder
	builder.WriteString("UsageLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	if v := _m.RequestedModel; v != nil {
		builder.WriteString("requested_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamModel; v != nil {
		builder.WriteString("upstream_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ChannelID; v != nil {
		builder.WriteString("channel_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ModelMappingChain; v != nil {
		builder.WriteString("model_mapping_chain=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BillingTier; v != nil {
		builder.WriteString("billing_tier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BillingMode; v != nil {
		builder.WriteString("billing_mode=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MediaProductID; v != nil {
		builder.WriteString("media_product_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MediaOfferID; v != nil {
		builder.WriteString("media_offer_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamPlatform; v != nil {
		builder.WriteString("upstream_platform=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SourceGroupID; v != nil {
		builder.WriteString("source_group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TrustedCostAmount; v != nil {
		builder.WriteString("trusted_cost_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TrustedCostUnit; v != nil {
		builder.WriteString("trusted_cost_unit=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TrustedCostSource; v != nil {
		builder.WriteString("trusted_cost_source=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TrustedCostVersion; v != nil {
		builder.WriteString("trusted_cost_version=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CustomerPriceVersion; v != nil {
		builder.WriteString("customer_price_version=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SubscriptionID; v != nil {
		builder.WriteString("subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_read_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_5m_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreation5mTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_1h_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreation1hTokens))
	builder.WriteString(", ")
	builder.WriteString("input_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputCost))
	builder.WriteString(", ")
	builder.WriteString("output_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputCost))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationCost))
	builder.WriteString(", ")
	builder.WriteString("cache_read_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadCost))
	builder.WriteString(", ")
	builder.WriteString("total_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCost))
	builder.WriteString(", ")
	builder.WriteString("actual_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActualCost))
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateMultiplier))
	builder.WriteString(", ")
	if v := _m.AccountRateMultiplier; v != nil {
		builder.WriteString("account_rate_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("billing_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillingType))
	builder.WriteString(", ")
	builder.WriteString("stream=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stream))
	builder.WriteString(", ")
	if v := _m.DurationMs; v != nil {
		builder.WriteString("duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FirstTokenMs; v != nil {
		builder.WriteString("first_token_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserAgent; v != nil {
		builder.WriteString("user_agent=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IPAddress; v != nil {
		builder.WriteString("ip_address=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("image_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageCount))
	builder.WriteString(", ")
	if v := _m.ImageSize; v != nil {
		builder.WriteString("image_size=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ImageInputSize; v != nil {
		builder.WriteString("image_input_size=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ImageOutputSize; v != nil {
		builder.WriteString("image_output_size=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ImageSizeSource; v != nil {
		builder.WriteString("image_size_source=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("image_size_breakdown=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageSizeBreakdown))
	builder.WriteString(", ")
	builder.WriteString("search_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SearchCount))
	builder.WriteString(", ")
	if v := _m.AudioMode; v != nil {
		builder.WriteString("audio_mode=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AudioUnits; v != nil {
		builder.WriteString("audio_units=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("cache_ttl_overridden=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheTTLOverridden))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsageLogs is a parsable slice of UsageLog.
type UsageLogs []*UsageLog
