import { mount } from '@vue/test-utils'
import { describe, expect, it, vi } from 'vitest'
import APIDocsView from '../APIDocsView.vue'

vi.mock('@/components/layout/AppLayout.vue', () => ({
  default: { template: '<div><slot /></div>' },
}))

describe('APIDocsView', () => {
  it('documents the eight supported Leonardo models and both protocols', () => {
    const wrapper = mount(APIDocsView)
    const text = wrapper.text()

    expect(text).toContain('OpenAI 兼容模式')
    expect(text).toContain('Leonardo 原生模式')
    expect(text).toContain('https://www.realyq.top/v1')
    expect(text).toContain('FLUX Schnell')
    expect(text).toContain('GPT Image 2')
    expect(text).toContain('Nano Banana 2')
    expect(text).toContain('Nano Banana 2 Lite')
    expect(text).toContain('Cinematic Kino')
    expect(text).toContain('Concept Art')
    expect(text).toContain('Graphic Design')
    expect(text).toContain('Illustrative Albedo')
    expect(wrapper.findAll('.model-section')).toHaveLength(14)
    expect(wrapper.findAll('.openai-manual')).toHaveLength(8)
    expect(wrapper.findAll('.raw-manual')).toHaveLength(8)
    expect(wrapper.find('#flux-schnell-openai').text()).toContain('FLUX Schnell · OpenAI 兼容模式')
    expect(wrapper.find('#flux-schnell-raw').text()).toContain('FLUX Schnell · Leonardo 原生模式')
    expect(wrapper.find('#gpt-image-2-openai').text()).toContain('GPT Image 2 · OpenAI 兼容模式')
    expect(wrapper.find('#gpt-image-2-raw').text()).toContain('GPT Image 2 · Leonardo 原生模式')
    expect(wrapper.find('#nano-banana-2-openai').text()).toContain('Nano Banana 2 · OpenAI 兼容模式')
    expect(wrapper.find('#nano-banana-2-raw').text()).toContain('Nano Banana 2 · Leonardo 原生模式')
    expect(wrapper.find('#nano-banana-2-lite-openai').text()).toContain('Nano Banana 2 Lite · OpenAI 兼容模式')
    expect(wrapper.find('#nano-banana-2-lite-raw').text()).toContain('Nano Banana 2 Lite · Leonardo 原生模式')
    expect(wrapper.find('#kino-xl-openai').text()).toContain('Cinematic Kino · OpenAI 兼容模式')
    expect(wrapper.find('#illustrative-albedo-raw').text()).toContain('Illustrative Albedo · Leonardo 原生模式')
    expect(text).not.toContain('grok-imagine')
    expect(wrapper.find('#gpt-image-2-openai').text()).toContain('最多 6 张参考图')
    expect(wrapper.find('#gpt-image-2-openai').text()).not.toContain('只允许一个 image 文件')
    expect(text).not.toContain('MiMo')
  })

  it('shows protocol-specific reference capabilities', () => {
    const wrapper = mount(APIDocsView)
    const text = wrapper.text()

    expect(text).toContain('多参考图')
    expect(text).toContain('内容参考')
    expect(text).toContain('风格参考')
    expect(text).toContain('文生图请求参数')
    expect(text).toContain('原生请求参数')
    expect(text).toContain('参考图怎么传？')
    expect(text).toContain('完整文生图示例')
    expect(text).toContain('异步提交响应')
    expect(text).toContain('/v1/images/edits')
    expect(text).toContain('/v1/media/generations/gen_123')
  })

  it('explains Nano quality through resolution instead of a low-quality mode', () => {
    const wrapper = mount(APIDocsView)
    const nano = wrapper.find('#nano-banana-2').text()
    const lite = wrapper.find('#nano-banana-2-lite').text()

    expect(nano).toContain('没有 low、medium、high 原生质量档')
    expect(nano).toContain('官方支持 1K、2K、4K')
    expect(nano).toContain('quality=low 仅用于接口兼容和本地计价')
    expect(lite).toContain('固定原生质量档')
    expect(lite).toContain('不是 low 低质量模型')
  })

  it('documents video and private compatible models with language guidance', () => {
    const wrapper = mount(APIDocsView)
    const text = wrapper.text()

    expect(text).toContain('Seedance 1.0 Pro Fast')
    expect(text).toContain('Motion 2.0 Fast')
    expect(text).toContain('Seedance 1.0 Pro')
    expect(text).toContain('Wan 2.7')
    expect(text).toContain('flux-2-klein-9b-kv')
    expect(text).toContain('minimax-h3')
    expect(text).toContain('/v1/videos/generations')
    expect(text).toContain('/v1/videos/{task_id}/content')
    expect(wrapper.findAll('.video-model-section')).toHaveLength(5)
    expect(wrapper.findAll('.video-openai-manual')).toHaveLength(4)
    expect(wrapper.findAll('.video-raw-manual')).toHaveLength(4)
    expect(wrapper.findAll('.video-openai-manual').find(section => section.attributes('id') === 'seedance-1.0-pro-fast-video-openai')?.text()).toContain('OpenAI 兼容格式')
    expect(wrapper.findAll('.video-raw-manual').find(section => section.attributes('id') === 'seedance-1.0-pro-fast-video-raw')?.text()).toContain('Leonardo 原生格式')
    expect(wrapper.findAll('.video-raw-manual').find(section => section.attributes('id') === 'motion_2.0-fast-video-raw')?.text()).toContain('不发送 duration')
    expect(wrapper.findAll('.video-raw-manual').find(section => section.attributes('id') === 'wan-2.7-video-raw')?.text()).toContain('parameters.resolution')
    expect(wrapper.findAll('.video-raw-manual').find(section => section.attributes('id') === 'wan-2.7-video-raw')?.text()).not.toContain('parameters.mode')
    expect(text).toContain('Idempotency-Key: video-request-001')
    expect(text).toContain('Idempotency-Key: video-raw-request-001')
    expect(wrapper.findAll('.video-model-section').find(section => section.attributes('id') === 'motion_2.0-fast')?.text()).toContain('"seconds": 0')
    expect(wrapper.findAll('.video-model-section').find(section => section.attributes('id') === 'wan-2.7')?.text()).toContain('2–10 秒')
    expect(wrapper.findAll('.video-model-section').find(section => section.attributes('id') === 'wan-2.7')?.text()).toContain('1080p')
    expect(wrapper.findAll('.video-model-section').find(section => section.attributes('id') === 'seedance-1.0-pro')?.text()).toContain('4/6/8/10 秒')
    expect(wrapper.find('#minimax-h3').text()).toContain('duration=5')
    expect(wrapper.find('#prompt-language').text()).toContain('RelayQ 不自动翻译')
    expect(wrapper.find('#kino-xl').text()).toContain('中文提示词主体严重偏离')
  })
})
