// Code generated by ent, DO NOT EDIT.

package mediaoffer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the mediaoffer type in the database.
	Label = "media_offer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldSourceGroupID holds the string denoting the source_group_id field in the database.
	FieldSourceGroupID = "source_group_id"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldOperations holds the string denoting the operations field in the database.
	FieldOperations = "operations"
	// FieldCapabilities holds the string denoting the capabilities field in the database.
	FieldCapabilities = "capabilities"
	// FieldCostRules holds the string denoting the cost_rules field in the database.
	FieldCostRules = "cost_rules"
	// FieldCostSource holds the string denoting the cost_source field in the database.
	FieldCostSource = "cost_source"
	// FieldCostVersion holds the string denoting the cost_version field in the database.
	FieldCostVersion = "cost_version"
	// FieldVerifiedAt holds the string denoting the verified_at field in the database.
	FieldVerifiedAt = "verified_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// EdgeSourceGroup holds the string denoting the source_group edge name in mutations.
	EdgeSourceGroup = "source_group"
	// Table holds the table name of the mediaoffer in the database.
	Table = "media_offers"
	// ProductTable is the table that holds the product relation/edge.
	ProductTable = "media_offers"
	// ProductInverseTable is the table name for the MediaProduct entity.
	// It exists in this package in order to avoid circular dependency with the "mediaproduct" package.
	ProductInverseTable = "media_products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_id"
	// SourceGroupTable is the table that holds the source_group relation/edge.
	SourceGroupTable = "media_offers"
	// SourceGroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	SourceGroupInverseTable = "groups"
	// SourceGroupColumn is the table column denoting the source_group relation/edge.
	SourceGroupColumn = "source_group_id"
)

// Columns holds all SQL columns for mediaoffer fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProductID,
	FieldProvider,
	FieldSourceGroupID,
	FieldUpstreamModel,
	FieldEnabled,
	FieldPriority,
	FieldOperations,
	FieldCapabilities,
	FieldCostRules,
	FieldCostSource,
	FieldCostVersion,
	FieldVerifiedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	PriorityValidator func(int) error
	// DefaultOperations holds the default value on creation for the "operations" field.
	DefaultOperations func() []string
	// DefaultCapabilities holds the default value on creation for the "capabilities" field.
	DefaultCapabilities func() map[string]interface{}
	// DefaultCostRules holds the default value on creation for the "cost_rules" field.
	DefaultCostRules func() map[string]interface{}
	// CostSourceValidator is a validator for the "cost_source" field. It is called by the builders before save.
	CostSourceValidator func(string) error
	// CostVersionValidator is a validator for the "cost_version" field. It is called by the builders before save.
	CostVersionValidator func(string) error
)

// OrderOption defines the ordering options for the MediaOffer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// BySourceGroupID orders the results by the source_group_id field.
func BySourceGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceGroupID, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByCostSource orders the results by the cost_source field.
func ByCostSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostSource, opts...).ToFunc()
}

// ByCostVersion orders the results by the cost_version field.
func ByCostVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostVersion, opts...).ToFunc()
}

// ByVerifiedAt orders the results by the verified_at field.
func ByVerifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerifiedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByProductField orders the results by product field.
func ByProductField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceGroupField orders the results by source_group field.
func BySourceGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
	)
}
func newSourceGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceGroupTable, SourceGroupColumn),
	)
}
