// Code generated by ent, DO NOT EDIT.

package mediaoffer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldProductID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldProvider, v))
}

// SourceGroupID applies equality check predicate on the "source_group_id" field. It's identical to SourceGroupIDEQ.
func SourceGroupID(v int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldSourceGroupID, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldUpstreamModel, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldEnabled, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldPriority, v))
}

// CostSource applies equality check predicate on the "cost_source" field. It's identical to CostSourceEQ.
func CostSource(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldCostSource, v))
}

// CostVersion applies equality check predicate on the "cost_version" field. It's identical to CostVersionEQ.
func CostVersion(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldCostVersion, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldVerifiedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNotIn(FieldProductID, vs...))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldContainsFold(FieldProvider, v))
}

// SourceGroupIDEQ applies the EQ predicate on the "source_group_id" field.
func SourceGroupIDEQ(v int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldSourceGroupID, v))
}

// SourceGroupIDNEQ applies the NEQ predicate on the "source_group_id" field.
func SourceGroupIDNEQ(v int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldSourceGroupID, v))
}

// SourceGroupIDIn applies the In predicate on the "source_group_id" field.
func SourceGroupIDIn(vs ...int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldIn(FieldSourceGroupID, vs...))
}

// SourceGroupIDNotIn applies the NotIn predicate on the "source_group_id" field.
func SourceGroupIDNotIn(vs ...int64) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNotIn(FieldSourceGroupID, vs...))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldEnabled, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLTE(FieldPriority, v))
}

// CostSourceEQ applies the EQ predicate on the "cost_source" field.
func CostSourceEQ(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldCostSource, v))
}

// CostSourceNEQ applies the NEQ predicate on the "cost_source" field.
func CostSourceNEQ(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldCostSource, v))
}

// CostSourceIn applies the In predicate on the "cost_source" field.
func CostSourceIn(vs ...string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldIn(FieldCostSource, vs...))
}

// CostSourceNotIn applies the NotIn predicate on the "cost_source" field.
func CostSourceNotIn(vs ...string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNotIn(FieldCostSource, vs...))
}

// CostSourceGT applies the GT predicate on the "cost_source" field.
func CostSourceGT(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGT(FieldCostSource, v))
}

// CostSourceGTE applies the GTE predicate on the "cost_source" field.
func CostSourceGTE(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGTE(FieldCostSource, v))
}

// CostSourceLT applies the LT predicate on the "cost_source" field.
func CostSourceLT(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLT(FieldCostSource, v))
}

// CostSourceLTE applies the LTE predicate on the "cost_source" field.
func CostSourceLTE(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLTE(FieldCostSource, v))
}

// CostSourceContains applies the Contains predicate on the "cost_source" field.
func CostSourceContains(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldContains(FieldCostSource, v))
}

// CostSourceHasPrefix applies the HasPrefix predicate on the "cost_source" field.
func CostSourceHasPrefix(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldHasPrefix(FieldCostSource, v))
}

// CostSourceHasSuffix applies the HasSuffix predicate on the "cost_source" field.
func CostSourceHasSuffix(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldHasSuffix(FieldCostSource, v))
}

// CostSourceEqualFold applies the EqualFold predicate on the "cost_source" field.
func CostSourceEqualFold(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEqualFold(FieldCostSource, v))
}

// CostSourceContainsFold applies the ContainsFold predicate on the "cost_source" field.
func CostSourceContainsFold(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldContainsFold(FieldCostSource, v))
}

// CostVersionEQ applies the EQ predicate on the "cost_version" field.
func CostVersionEQ(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldCostVersion, v))
}

// CostVersionNEQ applies the NEQ predicate on the "cost_version" field.
func CostVersionNEQ(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldCostVersion, v))
}

// CostVersionIn applies the In predicate on the "cost_version" field.
func CostVersionIn(vs ...string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldIn(FieldCostVersion, vs...))
}

// CostVersionNotIn applies the NotIn predicate on the "cost_version" field.
func CostVersionNotIn(vs ...string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNotIn(FieldCostVersion, vs...))
}

// CostVersionGT applies the GT predicate on the "cost_version" field.
func CostVersionGT(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGT(FieldCostVersion, v))
}

// CostVersionGTE applies the GTE predicate on the "cost_version" field.
func CostVersionGTE(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGTE(FieldCostVersion, v))
}

// CostVersionLT applies the LT predicate on the "cost_version" field.
func CostVersionLT(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLT(FieldCostVersion, v))
}

// CostVersionLTE applies the LTE predicate on the "cost_version" field.
func CostVersionLTE(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLTE(FieldCostVersion, v))
}

// CostVersionContains applies the Contains predicate on the "cost_version" field.
func CostVersionContains(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldContains(FieldCostVersion, v))
}

// CostVersionHasPrefix applies the HasPrefix predicate on the "cost_version" field.
func CostVersionHasPrefix(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldHasPrefix(FieldCostVersion, v))
}

// CostVersionHasSuffix applies the HasSuffix predicate on the "cost_version" field.
func CostVersionHasSuffix(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldHasSuffix(FieldCostVersion, v))
}

// CostVersionEqualFold applies the EqualFold predicate on the "cost_version" field.
func CostVersionEqualFold(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEqualFold(FieldCostVersion, v))
}

// CostVersionContainsFold applies the ContainsFold predicate on the "cost_version" field.
func CostVersionContainsFold(v string) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldContainsFold(FieldCostVersion, v))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLTE(FieldVerifiedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.MediaOffer {
	return predicate.MediaOffer(sql.FieldLTE(FieldExpiresAt, v))
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.MediaOffer {
	return predicate.MediaOffer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.MediaProduct) predicate.MediaOffer {
	return predicate.MediaOffer(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSourceGroup applies the HasEdge predicate on the "source_group" edge.
func HasSourceGroup() predicate.MediaOffer {
	return predicate.MediaOffer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceGroupTable, SourceGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceGroupWith applies the HasEdge predicate on the "source_group" edge with a given conditions (other predicates).
func HasSourceGroupWith(preds ...predicate.Group) predicate.MediaOffer {
	return predicate.MediaOffer(func(s *sql.Selector) {
		step := newSourceGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaOffer) predicate.MediaOffer {
	return predicate.MediaOffer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaOffer) predicate.MediaOffer {
	return predicate.MediaOffer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaOffer) predicate.MediaOffer {
	return predicate.MediaOffer(sql.NotPredicates(p))
}
