// Code generated by ent, DO NOT EDIT.

package mediaproduct

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublicModel applies equality check predicate on the "public_model" field. It's identical to PublicModelEQ.
func PublicModel(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldPublicModel, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldEnabled, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldLTE(FieldUpdatedAt, v))
}

// PublicModelEQ applies the EQ predicate on the "public_model" field.
func PublicModelEQ(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldPublicModel, v))
}

// PublicModelNEQ applies the NEQ predicate on the "public_model" field.
func PublicModelNEQ(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNEQ(FieldPublicModel, v))
}

// PublicModelIn applies the In predicate on the "public_model" field.
func PublicModelIn(vs ...string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldIn(FieldPublicModel, vs...))
}

// PublicModelNotIn applies the NotIn predicate on the "public_model" field.
func PublicModelNotIn(vs ...string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNotIn(FieldPublicModel, vs...))
}

// PublicModelGT applies the GT predicate on the "public_model" field.
func PublicModelGT(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldGT(FieldPublicModel, v))
}

// PublicModelGTE applies the GTE predicate on the "public_model" field.
func PublicModelGTE(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldGTE(FieldPublicModel, v))
}

// PublicModelLT applies the LT predicate on the "public_model" field.
func PublicModelLT(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldLT(FieldPublicModel, v))
}

// PublicModelLTE applies the LTE predicate on the "public_model" field.
func PublicModelLTE(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldLTE(FieldPublicModel, v))
}

// PublicModelContains applies the Contains predicate on the "public_model" field.
func PublicModelContains(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldContains(FieldPublicModel, v))
}

// PublicModelHasPrefix applies the HasPrefix predicate on the "public_model" field.
func PublicModelHasPrefix(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldHasPrefix(FieldPublicModel, v))
}

// PublicModelHasSuffix applies the HasSuffix predicate on the "public_model" field.
func PublicModelHasSuffix(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldHasSuffix(FieldPublicModel, v))
}

// PublicModelEqualFold applies the EqualFold predicate on the "public_model" field.
func PublicModelEqualFold(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEqualFold(FieldPublicModel, v))
}

// PublicModelContainsFold applies the ContainsFold predicate on the "public_model" field.
func PublicModelContainsFold(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldContainsFold(FieldPublicModel, v))
}

// ModalityEQ applies the EQ predicate on the "modality" field.
func ModalityEQ(v Modality) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldModality, v))
}

// ModalityNEQ applies the NEQ predicate on the "modality" field.
func ModalityNEQ(v Modality) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNEQ(FieldModality, v))
}

// ModalityIn applies the In predicate on the "modality" field.
func ModalityIn(vs ...Modality) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldIn(FieldModality, vs...))
}

// ModalityNotIn applies the NotIn predicate on the "modality" field.
func ModalityNotIn(vs ...Modality) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNotIn(FieldModality, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNEQ(FieldEnabled, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.MediaProduct {
	return predicate.MediaProduct(sql.FieldContainsFold(FieldDescription, v))
}

// HasPrices applies the HasEdge predicate on the "prices" edge.
func HasPrices() predicate.MediaProduct {
	return predicate.MediaProduct(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PricesTable, PricesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPricesWith applies the HasEdge predicate on the "prices" edge with a given conditions (other predicates).
func HasPricesWith(preds ...predicate.MediaProductPrice) predicate.MediaProduct {
	return predicate.MediaProduct(func(s *sql.Selector) {
		step := newPricesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOffers applies the HasEdge predicate on the "offers" edge.
func HasOffers() predicate.MediaProduct {
	return predicate.MediaProduct(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OffersTable, OffersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOffersWith applies the HasEdge predicate on the "offers" edge with a given conditions (other predicates).
func HasOffersWith(preds ...predicate.MediaOffer) predicate.MediaProduct {
	return predicate.MediaProduct(func(s *sql.Selector) {
		step := newOffersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.MediaProduct {
	return predicate.MediaProduct(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, GroupsTable, GroupsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.Group) predicate.MediaProduct {
	return predicate.MediaProduct(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaProduct) predicate.MediaProduct {
	return predicate.MediaProduct(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaProduct) predicate.MediaProduct {
	return predicate.MediaProduct(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaProduct) predicate.MediaProduct {
	return predicate.MediaProduct(sql.NotPredicates(p))
}
