// Code generated by ent, DO NOT EDIT.

package generationjob

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the generationjob type in the database.
	Label = "generation_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldModality holds the string denoting the modality field in the database.
	FieldModality = "modality"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldOfferID holds the string denoting the offer_id field in the database.
	FieldOfferID = "offer_id"
	// FieldSourceGroupID holds the string denoting the source_group_id field in the database.
	FieldSourceGroupID = "source_group_id"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldCustomerPriceVersion holds the string denoting the customer_price_version field in the database.
	FieldCustomerPriceVersion = "customer_price_version"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldUpstreamGenerationID holds the string denoting the upstream_generation_id field in the database.
	FieldUpstreamGenerationID = "upstream_generation_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUpstreamStatus holds the string denoting the upstream_status field in the database.
	FieldUpstreamStatus = "upstream_status"
	// FieldRequestHash holds the string denoting the request_hash field in the database.
	FieldRequestHash = "request_hash"
	// FieldRequestPayload holds the string denoting the request_payload field in the database.
	FieldRequestPayload = "request_payload"
	// FieldResultPayload holds the string denoting the result_payload field in the database.
	FieldResultPayload = "result_payload"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldOutputCount holds the string denoting the output_count field in the database.
	FieldOutputCount = "output_count"
	// FieldEstimatedUpstreamCostAmount holds the string denoting the estimated_upstream_cost_amount field in the database.
	FieldEstimatedUpstreamCostAmount = "estimated_upstream_cost_amount"
	// FieldEstimatedUpstreamCostUnit holds the string denoting the estimated_upstream_cost_unit field in the database.
	FieldEstimatedUpstreamCostUnit = "estimated_upstream_cost_unit"
	// FieldPricingSnapshotVersion holds the string denoting the pricing_snapshot_version field in the database.
	FieldPricingSnapshotVersion = "pricing_snapshot_version"
	// FieldPricingSource holds the string denoting the pricing_source field in the database.
	FieldPricingSource = "pricing_source"
	// FieldPricingMatchType holds the string denoting the pricing_match_type field in the database.
	FieldPricingMatchType = "pricing_match_type"
	// FieldActualUpstreamCostAmount holds the string denoting the actual_upstream_cost_amount field in the database.
	FieldActualUpstreamCostAmount = "actual_upstream_cost_amount"
	// FieldActualUpstreamCostUnit holds the string denoting the actual_upstream_cost_unit field in the database.
	FieldActualUpstreamCostUnit = "actual_upstream_cost_unit"
	// FieldCustomerCost holds the string denoting the customer_cost field in the database.
	FieldCustomerCost = "customer_cost"
	// FieldGrossMargin holds the string denoting the gross_margin field in the database.
	FieldGrossMargin = "gross_margin"
	// FieldCostVariance holds the string denoting the cost_variance field in the database.
	FieldCostVariance = "cost_variance"
	// FieldBillingStatus holds the string denoting the billing_status field in the database.
	FieldBillingStatus = "billing_status"
	// FieldBillingReference holds the string denoting the billing_reference field in the database.
	FieldBillingReference = "billing_reference"
	// FieldPollAttempts holds the string denoting the poll_attempts field in the database.
	FieldPollAttempts = "poll_attempts"
	// FieldNextPollAt holds the string denoting the next_poll_at field in the database.
	FieldNextPollAt = "next_poll_at"
	// FieldLastPolledAt holds the string denoting the last_polled_at field in the database.
	FieldLastPolledAt = "last_polled_at"
	// FieldSubmittedAt holds the string denoting the submitted_at field in the database.
	FieldSubmittedAt = "submitted_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldFailedAt holds the string denoting the failed_at field in the database.
	FieldFailedAt = "failed_at"
	// Table holds the table name of the generationjob in the database.
	Table = "generation_jobs"
)

// Columns holds all SQL columns for generationjob fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPublicID,
	FieldProvider,
	FieldModality,
	FieldModel,
	FieldUpstreamModel,
	FieldUserID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldProductID,
	FieldOfferID,
	FieldSourceGroupID,
	FieldOperation,
	FieldCustomerPriceVersion,
	FieldAccountID,
	FieldUpstreamGenerationID,
	FieldStatus,
	FieldUpstreamStatus,
	FieldRequestHash,
	FieldRequestPayload,
	FieldResultPayload,
	FieldErrorCode,
	FieldErrorMessage,
	FieldOutputCount,
	FieldEstimatedUpstreamCostAmount,
	FieldEstimatedUpstreamCostUnit,
	FieldPricingSnapshotVersion,
	FieldPricingSource,
	FieldPricingMatchType,
	FieldActualUpstreamCostAmount,
	FieldActualUpstreamCostUnit,
	FieldCustomerCost,
	FieldGrossMargin,
	FieldCostVariance,
	FieldBillingStatus,
	FieldBillingReference,
	FieldPollAttempts,
	FieldNextPollAt,
	FieldLastPolledAt,
	FieldSubmittedAt,
	FieldStartedAt,
	FieldCompletedAt,
	FieldFailedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PublicIDValidator is a validator for the "public_id" field. It is called by the builders before save.
	PublicIDValidator func(string) error
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ModalityValidator is a validator for the "modality" field. It is called by the builders before save.
	ModalityValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	OperationValidator func(string) error
	// CustomerPriceVersionValidator is a validator for the "customer_price_version" field. It is called by the builders before save.
	CustomerPriceVersionValidator func(string) error
	// UpstreamGenerationIDValidator is a validator for the "upstream_generation_id" field. It is called by the builders before save.
	UpstreamGenerationIDValidator func(string) error
	// UpstreamStatusValidator is a validator for the "upstream_status" field. It is called by the builders before save.
	UpstreamStatusValidator func(string) error
	// RequestHashValidator is a validator for the "request_hash" field. It is called by the builders before save.
	RequestHashValidator func(string) error
	// DefaultRequestPayload holds the default value on creation for the "request_payload" field.
	DefaultRequestPayload func() map[string]interface{}
	// DefaultResultPayload holds the default value on creation for the "result_payload" field.
	DefaultResultPayload func() map[string]interface{}
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultOutputCount holds the default value on creation for the "output_count" field.
	DefaultOutputCount int
	// OutputCountValidator is a validator for the "output_count" field. It is called by the builders before save.
	OutputCountValidator func(int) error
	// EstimatedUpstreamCostUnitValidator is a validator for the "estimated_upstream_cost_unit" field. It is called by the builders before save.
	EstimatedUpstreamCostUnitValidator func(string) error
	// PricingSnapshotVersionValidator is a validator for the "pricing_snapshot_version" field. It is called by the builders before save.
	PricingSnapshotVersionValidator func(string) error
	// PricingSourceValidator is a validator for the "pricing_source" field. It is called by the builders before save.
	PricingSourceValidator func(string) error
	// PricingMatchTypeValidator is a validator for the "pricing_match_type" field. It is called by the builders before save.
	PricingMatchTypeValidator func(string) error
	// ActualUpstreamCostUnitValidator is a validator for the "actual_upstream_cost_unit" field. It is called by the builders before save.
	ActualUpstreamCostUnitValidator func(string) error
	// BillingReferenceValidator is a validator for the "billing_reference" field. It is called by the builders before save.
	BillingReferenceValidator func(string) error
	// DefaultPollAttempts holds the default value on creation for the "poll_attempts" field.
	DefaultPollAttempts int
	// PollAttemptsValidator is a validator for the "poll_attempts" field. It is called by the builders before save.
	PollAttemptsValidator func(int) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusCreated is the default value of the Status enum.
const DefaultStatus = StatusCreated

// Status values.
const (
	StatusCreated    Status = "created"
	StatusSubmitting Status = "submitting"
	StatusQueued     Status = "queued"
	StatusRunning    Status = "running"
	StatusSucceeded  Status = "succeeded"
	StatusFailed     Status = "failed"
	StatusCancelled  Status = "cancelled"
	StatusUnknown    Status = "unknown"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusCreated, StatusSubmitting, StatusQueued, StatusRunning, StatusSucceeded, StatusFailed, StatusCancelled, StatusUnknown:
		return nil
	default:
		return fmt.Errorf("generationjob: invalid enum value for status field: %q", s)
	}
}

// BillingStatus defines the type for the "billing_status" enum field.
type BillingStatus string

// BillingStatusUnpriced is the default value of the BillingStatus enum.
const DefaultBillingStatus = BillingStatusUnpriced

// BillingStatus values.
const (
	BillingStatusUnpriced     BillingStatus = "unpriced"
	BillingStatusEstimated    BillingStatus = "estimated"
	BillingStatusReserved     BillingStatus = "reserved"
	BillingStatusSubmitted    BillingStatus = "submitted"
	BillingStatusSettled      BillingStatus = "settled"
	BillingStatusRefunded     BillingStatus = "refunded"
	BillingStatusManualReview BillingStatus = "manual_review"
)

func (bs BillingStatus) String() string {
	return string(bs)
}

// BillingStatusValidator is a validator for the "billing_status" field enum values. It is called by the builders before save.
func BillingStatusValidator(bs BillingStatus) error {
	switch bs {
	case BillingStatusUnpriced, BillingStatusEstimated, BillingStatusReserved, BillingStatusSubmitted, BillingStatusSettled, BillingStatusRefunded, BillingStatusManualReview:
		return nil
	default:
		return fmt.Errorf("generationjob: invalid enum value for billing_status field: %q", bs)
	}
}

// OrderOption defines the ordering options for the GenerationJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByModality orders the results by the modality field.
func ByModality(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModality, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByOfferID orders the results by the offer_id field.
func ByOfferID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOfferID, opts...).ToFunc()
}

// BySourceGroupID orders the results by the source_group_id field.
func BySourceGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceGroupID, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByCustomerPriceVersion orders the results by the customer_price_version field.
func ByCustomerPriceVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerPriceVersion, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByUpstreamGenerationID orders the results by the upstream_generation_id field.
func ByUpstreamGenerationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamGenerationID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUpstreamStatus orders the results by the upstream_status field.
func ByUpstreamStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamStatus, opts...).ToFunc()
}

// ByRequestHash orders the results by the request_hash field.
func ByRequestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestHash, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByOutputCount orders the results by the output_count field.
func ByOutputCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputCount, opts...).ToFunc()
}

// ByEstimatedUpstreamCostAmount orders the results by the estimated_upstream_cost_amount field.
func ByEstimatedUpstreamCostAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedUpstreamCostAmount, opts...).ToFunc()
}

// ByEstimatedUpstreamCostUnit orders the results by the estimated_upstream_cost_unit field.
func ByEstimatedUpstreamCostUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedUpstreamCostUnit, opts...).ToFunc()
}

// ByPricingSnapshotVersion orders the results by the pricing_snapshot_version field.
func ByPricingSnapshotVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricingSnapshotVersion, opts...).ToFunc()
}

// ByPricingSource orders the results by the pricing_source field.
func ByPricingSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricingSource, opts...).ToFunc()
}

// ByPricingMatchType orders the results by the pricing_match_type field.
func ByPricingMatchType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricingMatchType, opts...).ToFunc()
}

// ByActualUpstreamCostAmount orders the results by the actual_upstream_cost_amount field.
func ByActualUpstreamCostAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualUpstreamCostAmount, opts...).ToFunc()
}

// ByActualUpstreamCostUnit orders the results by the actual_upstream_cost_unit field.
func ByActualUpstreamCostUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualUpstreamCostUnit, opts...).ToFunc()
}

// ByCustomerCost orders the results by the customer_cost field.
func ByCustomerCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerCost, opts...).ToFunc()
}

// ByGrossMargin orders the results by the gross_margin field.
func ByGrossMargin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrossMargin, opts...).ToFunc()
}

// ByCostVariance orders the results by the cost_variance field.
func ByCostVariance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostVariance, opts...).ToFunc()
}

// ByBillingStatus orders the results by the billing_status field.
func ByBillingStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingStatus, opts...).ToFunc()
}

// ByBillingReference orders the results by the billing_reference field.
func ByBillingReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingReference, opts...).ToFunc()
}

// ByPollAttempts orders the results by the poll_attempts field.
func ByPollAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPollAttempts, opts...).ToFunc()
}

// ByNextPollAt orders the results by the next_poll_at field.
func ByNextPollAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextPollAt, opts...).ToFunc()
}

// ByLastPolledAt orders the results by the last_polled_at field.
func ByLastPolledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPolledAt, opts...).ToFunc()
}

// BySubmittedAt orders the results by the submitted_at field.
func BySubmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByFailedAt orders the results by the failed_at field.
func ByFailedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedAt, opts...).ToFunc()
}
