// Code generated by ent, DO NOT EDIT.

package generationjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldPublicID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldProvider, v))
}

// Modality applies equality check predicate on the "modality" field. It's identical to ModalityEQ.
func Modality(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldModality, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldModel, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldUpstreamModel, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldGroupID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldAccountID, v))
}

// UpstreamGenerationID applies equality check predicate on the "upstream_generation_id" field. It's identical to UpstreamGenerationIDEQ.
func UpstreamGenerationID(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldUpstreamGenerationID, v))
}

// UpstreamStatus applies equality check predicate on the "upstream_status" field. It's identical to UpstreamStatusEQ.
func UpstreamStatus(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldUpstreamStatus, v))
}

// RequestHash applies equality check predicate on the "request_hash" field. It's identical to RequestHashEQ.
func RequestHash(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldRequestHash, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldErrorMessage, v))
}

// OutputCount applies equality check predicate on the "output_count" field. It's identical to OutputCountEQ.
func OutputCount(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldOutputCount, v))
}

// EstimatedUpstreamCostAmount applies equality check predicate on the "estimated_upstream_cost_amount" field. It's identical to EstimatedUpstreamCostAmountEQ.
func EstimatedUpstreamCostAmount(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldEstimatedUpstreamCostAmount, v))
}

// EstimatedUpstreamCostUnit applies equality check predicate on the "estimated_upstream_cost_unit" field. It's identical to EstimatedUpstreamCostUnitEQ.
func EstimatedUpstreamCostUnit(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldEstimatedUpstreamCostUnit, v))
}

// PricingSnapshotVersion applies equality check predicate on the "pricing_snapshot_version" field. It's identical to PricingSnapshotVersionEQ.
func PricingSnapshotVersion(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldPricingSnapshotVersion, v))
}

// PricingSource applies equality check predicate on the "pricing_source" field. It's identical to PricingSourceEQ.
func PricingSource(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldPricingSource, v))
}

// PricingMatchType applies equality check predicate on the "pricing_match_type" field. It's identical to PricingMatchTypeEQ.
func PricingMatchType(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldPricingMatchType, v))
}

// ActualUpstreamCostAmount applies equality check predicate on the "actual_upstream_cost_amount" field. It's identical to ActualUpstreamCostAmountEQ.
func ActualUpstreamCostAmount(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldActualUpstreamCostAmount, v))
}

// ActualUpstreamCostUnit applies equality check predicate on the "actual_upstream_cost_unit" field. It's identical to ActualUpstreamCostUnitEQ.
func ActualUpstreamCostUnit(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldActualUpstreamCostUnit, v))
}

// CustomerCost applies equality check predicate on the "customer_cost" field. It's identical to CustomerCostEQ.
func CustomerCost(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldCustomerCost, v))
}

// GrossMargin applies equality check predicate on the "gross_margin" field. It's identical to GrossMarginEQ.
func GrossMargin(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldGrossMargin, v))
}

// CostVariance applies equality check predicate on the "cost_variance" field. It's identical to CostVarianceEQ.
func CostVariance(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldCostVariance, v))
}

// BillingReference applies equality check predicate on the "billing_reference" field. It's identical to BillingReferenceEQ.
func BillingReference(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldBillingReference, v))
}

// PollAttempts applies equality check predicate on the "poll_attempts" field. It's identical to PollAttemptsEQ.
func PollAttempts(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldPollAttempts, v))
}

// NextPollAt applies equality check predicate on the "next_poll_at" field. It's identical to NextPollAtEQ.
func NextPollAt(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldNextPollAt, v))
}

// LastPolledAt applies equality check predicate on the "last_polled_at" field. It's identical to LastPolledAtEQ.
func LastPolledAt(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldLastPolledAt, v))
}

// SubmittedAt applies equality check predicate on the "submitted_at" field. It's identical to SubmittedAtEQ.
func SubmittedAt(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldSubmittedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldCompletedAt, v))
}

// FailedAt applies equality check predicate on the "failed_at" field. It's identical to FailedAtEQ.
func FailedAt(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldFailedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldPublicID, v))
}

// PublicIDContains applies the Contains predicate on the "public_id" field.
func PublicIDContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldPublicID, v))
}

// PublicIDHasPrefix applies the HasPrefix predicate on the "public_id" field.
func PublicIDHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldPublicID, v))
}

// PublicIDHasSuffix applies the HasSuffix predicate on the "public_id" field.
func PublicIDHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldPublicID, v))
}

// PublicIDEqualFold applies the EqualFold predicate on the "public_id" field.
func PublicIDEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldPublicID, v))
}

// PublicIDContainsFold applies the ContainsFold predicate on the "public_id" field.
func PublicIDContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldPublicID, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldProvider, v))
}

// ModalityEQ applies the EQ predicate on the "modality" field.
func ModalityEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldModality, v))
}

// ModalityNEQ applies the NEQ predicate on the "modality" field.
func ModalityNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldModality, v))
}

// ModalityIn applies the In predicate on the "modality" field.
func ModalityIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldModality, vs...))
}

// ModalityNotIn applies the NotIn predicate on the "modality" field.
func ModalityNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldModality, vs...))
}

// ModalityGT applies the GT predicate on the "modality" field.
func ModalityGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldModality, v))
}

// ModalityGTE applies the GTE predicate on the "modality" field.
func ModalityGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldModality, v))
}

// ModalityLT applies the LT predicate on the "modality" field.
func ModalityLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldModality, v))
}

// ModalityLTE applies the LTE predicate on the "modality" field.
func ModalityLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldModality, v))
}

// ModalityContains applies the Contains predicate on the "modality" field.
func ModalityContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldModality, v))
}

// ModalityHasPrefix applies the HasPrefix predicate on the "modality" field.
func ModalityHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldModality, v))
}

// ModalityHasSuffix applies the HasSuffix predicate on the "modality" field.
func ModalityHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldModality, v))
}

// ModalityEqualFold applies the EqualFold predicate on the "modality" field.
func ModalityEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldModality, v))
}

// ModalityContainsFold applies the ContainsFold predicate on the "modality" field.
func ModalityContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldModality, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldModel, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldAPIKeyID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldGroupID))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldAccountID, v))
}

// UpstreamGenerationIDEQ applies the EQ predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldUpstreamGenerationID, v))
}

// UpstreamGenerationIDNEQ applies the NEQ predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldUpstreamGenerationID, v))
}

// UpstreamGenerationIDIn applies the In predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldUpstreamGenerationID, vs...))
}

// UpstreamGenerationIDNotIn applies the NotIn predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldUpstreamGenerationID, vs...))
}

// UpstreamGenerationIDGT applies the GT predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldUpstreamGenerationID, v))
}

// UpstreamGenerationIDGTE applies the GTE predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldUpstreamGenerationID, v))
}

// UpstreamGenerationIDLT applies the LT predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldUpstreamGenerationID, v))
}

// UpstreamGenerationIDLTE applies the LTE predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldUpstreamGenerationID, v))
}

// UpstreamGenerationIDContains applies the Contains predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldUpstreamGenerationID, v))
}

// UpstreamGenerationIDHasPrefix applies the HasPrefix predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldUpstreamGenerationID, v))
}

// UpstreamGenerationIDHasSuffix applies the HasSuffix predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldUpstreamGenerationID, v))
}

// UpstreamGenerationIDIsNil applies the IsNil predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldUpstreamGenerationID))
}

// UpstreamGenerationIDNotNil applies the NotNil predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldUpstreamGenerationID))
}

// UpstreamGenerationIDEqualFold applies the EqualFold predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldUpstreamGenerationID, v))
}

// UpstreamGenerationIDContainsFold applies the ContainsFold predicate on the "upstream_generation_id" field.
func UpstreamGenerationIDContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldUpstreamGenerationID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldStatus, vs...))
}

// UpstreamStatusEQ applies the EQ predicate on the "upstream_status" field.
func UpstreamStatusEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldUpstreamStatus, v))
}

// UpstreamStatusNEQ applies the NEQ predicate on the "upstream_status" field.
func UpstreamStatusNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldUpstreamStatus, v))
}

// UpstreamStatusIn applies the In predicate on the "upstream_status" field.
func UpstreamStatusIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldUpstreamStatus, vs...))
}

// UpstreamStatusNotIn applies the NotIn predicate on the "upstream_status" field.
func UpstreamStatusNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldUpstreamStatus, vs...))
}

// UpstreamStatusGT applies the GT predicate on the "upstream_status" field.
func UpstreamStatusGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldUpstreamStatus, v))
}

// UpstreamStatusGTE applies the GTE predicate on the "upstream_status" field.
func UpstreamStatusGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldUpstreamStatus, v))
}

// UpstreamStatusLT applies the LT predicate on the "upstream_status" field.
func UpstreamStatusLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldUpstreamStatus, v))
}

// UpstreamStatusLTE applies the LTE predicate on the "upstream_status" field.
func UpstreamStatusLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldUpstreamStatus, v))
}

// UpstreamStatusContains applies the Contains predicate on the "upstream_status" field.
func UpstreamStatusContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldUpstreamStatus, v))
}

// UpstreamStatusHasPrefix applies the HasPrefix predicate on the "upstream_status" field.
func UpstreamStatusHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldUpstreamStatus, v))
}

// UpstreamStatusHasSuffix applies the HasSuffix predicate on the "upstream_status" field.
func UpstreamStatusHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldUpstreamStatus, v))
}

// UpstreamStatusIsNil applies the IsNil predicate on the "upstream_status" field.
func UpstreamStatusIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldUpstreamStatus))
}

// UpstreamStatusNotNil applies the NotNil predicate on the "upstream_status" field.
func UpstreamStatusNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldUpstreamStatus))
}

// UpstreamStatusEqualFold applies the EqualFold predicate on the "upstream_status" field.
func UpstreamStatusEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldUpstreamStatus, v))
}

// UpstreamStatusContainsFold applies the ContainsFold predicate on the "upstream_status" field.
func UpstreamStatusContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldUpstreamStatus, v))
}

// RequestHashEQ applies the EQ predicate on the "request_hash" field.
func RequestHashEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldRequestHash, v))
}

// RequestHashNEQ applies the NEQ predicate on the "request_hash" field.
func RequestHashNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldRequestHash, v))
}

// RequestHashIn applies the In predicate on the "request_hash" field.
func RequestHashIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldRequestHash, vs...))
}

// RequestHashNotIn applies the NotIn predicate on the "request_hash" field.
func RequestHashNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldRequestHash, vs...))
}

// RequestHashGT applies the GT predicate on the "request_hash" field.
func RequestHashGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldRequestHash, v))
}

// RequestHashGTE applies the GTE predicate on the "request_hash" field.
func RequestHashGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldRequestHash, v))
}

// RequestHashLT applies the LT predicate on the "request_hash" field.
func RequestHashLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldRequestHash, v))
}

// RequestHashLTE applies the LTE predicate on the "request_hash" field.
func RequestHashLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldRequestHash, v))
}

// RequestHashContains applies the Contains predicate on the "request_hash" field.
func RequestHashContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldRequestHash, v))
}

// RequestHashHasPrefix applies the HasPrefix predicate on the "request_hash" field.
func RequestHashHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldRequestHash, v))
}

// RequestHashHasSuffix applies the HasSuffix predicate on the "request_hash" field.
func RequestHashHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldRequestHash, v))
}

// RequestHashEqualFold applies the EqualFold predicate on the "request_hash" field.
func RequestHashEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldRequestHash, v))
}

// RequestHashContainsFold applies the ContainsFold predicate on the "request_hash" field.
func RequestHashContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldRequestHash, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldErrorMessage, v))
}

// OutputCountEQ applies the EQ predicate on the "output_count" field.
func OutputCountEQ(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldOutputCount, v))
}

// OutputCountNEQ applies the NEQ predicate on the "output_count" field.
func OutputCountNEQ(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldOutputCount, v))
}

// OutputCountIn applies the In predicate on the "output_count" field.
func OutputCountIn(vs ...int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldOutputCount, vs...))
}

// OutputCountNotIn applies the NotIn predicate on the "output_count" field.
func OutputCountNotIn(vs ...int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldOutputCount, vs...))
}

// OutputCountGT applies the GT predicate on the "output_count" field.
func OutputCountGT(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldOutputCount, v))
}

// OutputCountGTE applies the GTE predicate on the "output_count" field.
func OutputCountGTE(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldOutputCount, v))
}

// OutputCountLT applies the LT predicate on the "output_count" field.
func OutputCountLT(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldOutputCount, v))
}

// OutputCountLTE applies the LTE predicate on the "output_count" field.
func OutputCountLTE(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldOutputCount, v))
}

// EstimatedUpstreamCostAmountEQ applies the EQ predicate on the "estimated_upstream_cost_amount" field.
func EstimatedUpstreamCostAmountEQ(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldEstimatedUpstreamCostAmount, v))
}

// EstimatedUpstreamCostAmountNEQ applies the NEQ predicate on the "estimated_upstream_cost_amount" field.
func EstimatedUpstreamCostAmountNEQ(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldEstimatedUpstreamCostAmount, v))
}

// EstimatedUpstreamCostAmountIn applies the In predicate on the "estimated_upstream_cost_amount" field.
func EstimatedUpstreamCostAmountIn(vs ...*decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldEstimatedUpstreamCostAmount, vs...))
}

// EstimatedUpstreamCostAmountNotIn applies the NotIn predicate on the "estimated_upstream_cost_amount" field.
func EstimatedUpstreamCostAmountNotIn(vs ...*decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldEstimatedUpstreamCostAmount, vs...))
}

// EstimatedUpstreamCostAmountGT applies the GT predicate on the "estimated_upstream_cost_amount" field.
func EstimatedUpstreamCostAmountGT(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldEstimatedUpstreamCostAmount, v))
}

// EstimatedUpstreamCostAmountGTE applies the GTE predicate on the "estimated_upstream_cost_amount" field.
func EstimatedUpstreamCostAmountGTE(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldEstimatedUpstreamCostAmount, v))
}

// EstimatedUpstreamCostAmountLT applies the LT predicate on the "estimated_upstream_cost_amount" field.
func EstimatedUpstreamCostAmountLT(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldEstimatedUpstreamCostAmount, v))
}

// EstimatedUpstreamCostAmountLTE applies the LTE predicate on the "estimated_upstream_cost_amount" field.
func EstimatedUpstreamCostAmountLTE(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldEstimatedUpstreamCostAmount, v))
}

// EstimatedUpstreamCostAmountIsNil applies the IsNil predicate on the "estimated_upstream_cost_amount" field.
func EstimatedUpstreamCostAmountIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldEstimatedUpstreamCostAmount))
}

// EstimatedUpstreamCostAmountNotNil applies the NotNil predicate on the "estimated_upstream_cost_amount" field.
func EstimatedUpstreamCostAmountNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldEstimatedUpstreamCostAmount))
}

// EstimatedUpstreamCostUnitEQ applies the EQ predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldEstimatedUpstreamCostUnit, v))
}

// EstimatedUpstreamCostUnitNEQ applies the NEQ predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldEstimatedUpstreamCostUnit, v))
}

// EstimatedUpstreamCostUnitIn applies the In predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldEstimatedUpstreamCostUnit, vs...))
}

// EstimatedUpstreamCostUnitNotIn applies the NotIn predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldEstimatedUpstreamCostUnit, vs...))
}

// EstimatedUpstreamCostUnitGT applies the GT predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldEstimatedUpstreamCostUnit, v))
}

// EstimatedUpstreamCostUnitGTE applies the GTE predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldEstimatedUpstreamCostUnit, v))
}

// EstimatedUpstreamCostUnitLT applies the LT predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldEstimatedUpstreamCostUnit, v))
}

// EstimatedUpstreamCostUnitLTE applies the LTE predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldEstimatedUpstreamCostUnit, v))
}

// EstimatedUpstreamCostUnitContains applies the Contains predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldEstimatedUpstreamCostUnit, v))
}

// EstimatedUpstreamCostUnitHasPrefix applies the HasPrefix predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldEstimatedUpstreamCostUnit, v))
}

// EstimatedUpstreamCostUnitHasSuffix applies the HasSuffix predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldEstimatedUpstreamCostUnit, v))
}

// EstimatedUpstreamCostUnitIsNil applies the IsNil predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldEstimatedUpstreamCostUnit))
}

// EstimatedUpstreamCostUnitNotNil applies the NotNil predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldEstimatedUpstreamCostUnit))
}

// EstimatedUpstreamCostUnitEqualFold applies the EqualFold predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldEstimatedUpstreamCostUnit, v))
}

// EstimatedUpstreamCostUnitContainsFold applies the ContainsFold predicate on the "estimated_upstream_cost_unit" field.
func EstimatedUpstreamCostUnitContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldEstimatedUpstreamCostUnit, v))
}

// PricingSnapshotVersionEQ applies the EQ predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldPricingSnapshotVersion, v))
}

// PricingSnapshotVersionNEQ applies the NEQ predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldPricingSnapshotVersion, v))
}

// PricingSnapshotVersionIn applies the In predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldPricingSnapshotVersion, vs...))
}

// PricingSnapshotVersionNotIn applies the NotIn predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldPricingSnapshotVersion, vs...))
}

// PricingSnapshotVersionGT applies the GT predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldPricingSnapshotVersion, v))
}

// PricingSnapshotVersionGTE applies the GTE predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldPricingSnapshotVersion, v))
}

// PricingSnapshotVersionLT applies the LT predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldPricingSnapshotVersion, v))
}

// PricingSnapshotVersionLTE applies the LTE predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldPricingSnapshotVersion, v))
}

// PricingSnapshotVersionContains applies the Contains predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldPricingSnapshotVersion, v))
}

// PricingSnapshotVersionHasPrefix applies the HasPrefix predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldPricingSnapshotVersion, v))
}

// PricingSnapshotVersionHasSuffix applies the HasSuffix predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldPricingSnapshotVersion, v))
}

// PricingSnapshotVersionIsNil applies the IsNil predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldPricingSnapshotVersion))
}

// PricingSnapshotVersionNotNil applies the NotNil predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldPricingSnapshotVersion))
}

// PricingSnapshotVersionEqualFold applies the EqualFold predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldPricingSnapshotVersion, v))
}

// PricingSnapshotVersionContainsFold applies the ContainsFold predicate on the "pricing_snapshot_version" field.
func PricingSnapshotVersionContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldPricingSnapshotVersion, v))
}

// PricingSourceEQ applies the EQ predicate on the "pricing_source" field.
func PricingSourceEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldPricingSource, v))
}

// PricingSourceNEQ applies the NEQ predicate on the "pricing_source" field.
func PricingSourceNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldPricingSource, v))
}

// PricingSourceIn applies the In predicate on the "pricing_source" field.
func PricingSourceIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldPricingSource, vs...))
}

// PricingSourceNotIn applies the NotIn predicate on the "pricing_source" field.
func PricingSourceNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldPricingSource, vs...))
}

// PricingSourceGT applies the GT predicate on the "pricing_source" field.
func PricingSourceGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldPricingSource, v))
}

// PricingSourceGTE applies the GTE predicate on the "pricing_source" field.
func PricingSourceGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldPricingSource, v))
}

// PricingSourceLT applies the LT predicate on the "pricing_source" field.
func PricingSourceLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldPricingSource, v))
}

// PricingSourceLTE applies the LTE predicate on the "pricing_source" field.
func PricingSourceLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldPricingSource, v))
}

// PricingSourceContains applies the Contains predicate on the "pricing_source" field.
func PricingSourceContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldPricingSource, v))
}

// PricingSourceHasPrefix applies the HasPrefix predicate on the "pricing_source" field.
func PricingSourceHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldPricingSource, v))
}

// PricingSourceHasSuffix applies the HasSuffix predicate on the "pricing_source" field.
func PricingSourceHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldPricingSource, v))
}

// PricingSourceIsNil applies the IsNil predicate on the "pricing_source" field.
func PricingSourceIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldPricingSource))
}

// PricingSourceNotNil applies the NotNil predicate on the "pricing_source" field.
func PricingSourceNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldPricingSource))
}

// PricingSourceEqualFold applies the EqualFold predicate on the "pricing_source" field.
func PricingSourceEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldPricingSource, v))
}

// PricingSourceContainsFold applies the ContainsFold predicate on the "pricing_source" field.
func PricingSourceContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldPricingSource, v))
}

// PricingMatchTypeEQ applies the EQ predicate on the "pricing_match_type" field.
func PricingMatchTypeEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldPricingMatchType, v))
}

// PricingMatchTypeNEQ applies the NEQ predicate on the "pricing_match_type" field.
func PricingMatchTypeNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldPricingMatchType, v))
}

// PricingMatchTypeIn applies the In predicate on the "pricing_match_type" field.
func PricingMatchTypeIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldPricingMatchType, vs...))
}

// PricingMatchTypeNotIn applies the NotIn predicate on the "pricing_match_type" field.
func PricingMatchTypeNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldPricingMatchType, vs...))
}

// PricingMatchTypeGT applies the GT predicate on the "pricing_match_type" field.
func PricingMatchTypeGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldPricingMatchType, v))
}

// PricingMatchTypeGTE applies the GTE predicate on the "pricing_match_type" field.
func PricingMatchTypeGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldPricingMatchType, v))
}

// PricingMatchTypeLT applies the LT predicate on the "pricing_match_type" field.
func PricingMatchTypeLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldPricingMatchType, v))
}

// PricingMatchTypeLTE applies the LTE predicate on the "pricing_match_type" field.
func PricingMatchTypeLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldPricingMatchType, v))
}

// PricingMatchTypeContains applies the Contains predicate on the "pricing_match_type" field.
func PricingMatchTypeContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldPricingMatchType, v))
}

// PricingMatchTypeHasPrefix applies the HasPrefix predicate on the "pricing_match_type" field.
func PricingMatchTypeHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldPricingMatchType, v))
}

// PricingMatchTypeHasSuffix applies the HasSuffix predicate on the "pricing_match_type" field.
func PricingMatchTypeHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldPricingMatchType, v))
}

// PricingMatchTypeIsNil applies the IsNil predicate on the "pricing_match_type" field.
func PricingMatchTypeIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldPricingMatchType))
}

// PricingMatchTypeNotNil applies the NotNil predicate on the "pricing_match_type" field.
func PricingMatchTypeNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldPricingMatchType))
}

// PricingMatchTypeEqualFold applies the EqualFold predicate on the "pricing_match_type" field.
func PricingMatchTypeEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldPricingMatchType, v))
}

// PricingMatchTypeContainsFold applies the ContainsFold predicate on the "pricing_match_type" field.
func PricingMatchTypeContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldPricingMatchType, v))
}

// ActualUpstreamCostAmountEQ applies the EQ predicate on the "actual_upstream_cost_amount" field.
func ActualUpstreamCostAmountEQ(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldActualUpstreamCostAmount, v))
}

// ActualUpstreamCostAmountNEQ applies the NEQ predicate on the "actual_upstream_cost_amount" field.
func ActualUpstreamCostAmountNEQ(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldActualUpstreamCostAmount, v))
}

// ActualUpstreamCostAmountIn applies the In predicate on the "actual_upstream_cost_amount" field.
func ActualUpstreamCostAmountIn(vs ...*decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldActualUpstreamCostAmount, vs...))
}

// ActualUpstreamCostAmountNotIn applies the NotIn predicate on the "actual_upstream_cost_amount" field.
func ActualUpstreamCostAmountNotIn(vs ...*decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldActualUpstreamCostAmount, vs...))
}

// ActualUpstreamCostAmountGT applies the GT predicate on the "actual_upstream_cost_amount" field.
func ActualUpstreamCostAmountGT(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldActualUpstreamCostAmount, v))
}

// ActualUpstreamCostAmountGTE applies the GTE predicate on the "actual_upstream_cost_amount" field.
func ActualUpstreamCostAmountGTE(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldActualUpstreamCostAmount, v))
}

// ActualUpstreamCostAmountLT applies the LT predicate on the "actual_upstream_cost_amount" field.
func ActualUpstreamCostAmountLT(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldActualUpstreamCostAmount, v))
}

// ActualUpstreamCostAmountLTE applies the LTE predicate on the "actual_upstream_cost_amount" field.
func ActualUpstreamCostAmountLTE(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldActualUpstreamCostAmount, v))
}

// ActualUpstreamCostAmountIsNil applies the IsNil predicate on the "actual_upstream_cost_amount" field.
func ActualUpstreamCostAmountIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldActualUpstreamCostAmount))
}

// ActualUpstreamCostAmountNotNil applies the NotNil predicate on the "actual_upstream_cost_amount" field.
func ActualUpstreamCostAmountNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldActualUpstreamCostAmount))
}

// ActualUpstreamCostUnitEQ applies the EQ predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldActualUpstreamCostUnit, v))
}

// ActualUpstreamCostUnitNEQ applies the NEQ predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldActualUpstreamCostUnit, v))
}

// ActualUpstreamCostUnitIn applies the In predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldActualUpstreamCostUnit, vs...))
}

// ActualUpstreamCostUnitNotIn applies the NotIn predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldActualUpstreamCostUnit, vs...))
}

// ActualUpstreamCostUnitGT applies the GT predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldActualUpstreamCostUnit, v))
}

// ActualUpstreamCostUnitGTE applies the GTE predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldActualUpstreamCostUnit, v))
}

// ActualUpstreamCostUnitLT applies the LT predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldActualUpstreamCostUnit, v))
}

// ActualUpstreamCostUnitLTE applies the LTE predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldActualUpstreamCostUnit, v))
}

// ActualUpstreamCostUnitContains applies the Contains predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldActualUpstreamCostUnit, v))
}

// ActualUpstreamCostUnitHasPrefix applies the HasPrefix predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldActualUpstreamCostUnit, v))
}

// ActualUpstreamCostUnitHasSuffix applies the HasSuffix predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldActualUpstreamCostUnit, v))
}

// ActualUpstreamCostUnitIsNil applies the IsNil predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldActualUpstreamCostUnit))
}

// ActualUpstreamCostUnitNotNil applies the NotNil predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldActualUpstreamCostUnit))
}

// ActualUpstreamCostUnitEqualFold applies the EqualFold predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldActualUpstreamCostUnit, v))
}

// ActualUpstreamCostUnitContainsFold applies the ContainsFold predicate on the "actual_upstream_cost_unit" field.
func ActualUpstreamCostUnitContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldActualUpstreamCostUnit, v))
}

// CustomerCostEQ applies the EQ predicate on the "customer_cost" field.
func CustomerCostEQ(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldCustomerCost, v))
}

// CustomerCostNEQ applies the NEQ predicate on the "customer_cost" field.
func CustomerCostNEQ(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldCustomerCost, v))
}

// CustomerCostIn applies the In predicate on the "customer_cost" field.
func CustomerCostIn(vs ...*decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldCustomerCost, vs...))
}

// CustomerCostNotIn applies the NotIn predicate on the "customer_cost" field.
func CustomerCostNotIn(vs ...*decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldCustomerCost, vs...))
}

// CustomerCostGT applies the GT predicate on the "customer_cost" field.
func CustomerCostGT(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldCustomerCost, v))
}

// CustomerCostGTE applies the GTE predicate on the "customer_cost" field.
func CustomerCostGTE(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldCustomerCost, v))
}

// CustomerCostLT applies the LT predicate on the "customer_cost" field.
func CustomerCostLT(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldCustomerCost, v))
}

// CustomerCostLTE applies the LTE predicate on the "customer_cost" field.
func CustomerCostLTE(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldCustomerCost, v))
}

// CustomerCostIsNil applies the IsNil predicate on the "customer_cost" field.
func CustomerCostIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldCustomerCost))
}

// CustomerCostNotNil applies the NotNil predicate on the "customer_cost" field.
func CustomerCostNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldCustomerCost))
}

// GrossMarginEQ applies the EQ predicate on the "gross_margin" field.
func GrossMarginEQ(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldGrossMargin, v))
}

// GrossMarginNEQ applies the NEQ predicate on the "gross_margin" field.
func GrossMarginNEQ(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldGrossMargin, v))
}

// GrossMarginIn applies the In predicate on the "gross_margin" field.
func GrossMarginIn(vs ...*decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldGrossMargin, vs...))
}

// GrossMarginNotIn applies the NotIn predicate on the "gross_margin" field.
func GrossMarginNotIn(vs ...*decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldGrossMargin, vs...))
}

// GrossMarginGT applies the GT predicate on the "gross_margin" field.
func GrossMarginGT(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldGrossMargin, v))
}

// GrossMarginGTE applies the GTE predicate on the "gross_margin" field.
func GrossMarginGTE(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldGrossMargin, v))
}

// GrossMarginLT applies the LT predicate on the "gross_margin" field.
func GrossMarginLT(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldGrossMargin, v))
}

// GrossMarginLTE applies the LTE predicate on the "gross_margin" field.
func GrossMarginLTE(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldGrossMargin, v))
}

// GrossMarginIsNil applies the IsNil predicate on the "gross_margin" field.
func GrossMarginIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldGrossMargin))
}

// GrossMarginNotNil applies the NotNil predicate on the "gross_margin" field.
func GrossMarginNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldGrossMargin))
}

// CostVarianceEQ applies the EQ predicate on the "cost_variance" field.
func CostVarianceEQ(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldCostVariance, v))
}

// CostVarianceNEQ applies the NEQ predicate on the "cost_variance" field.
func CostVarianceNEQ(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldCostVariance, v))
}

// CostVarianceIn applies the In predicate on the "cost_variance" field.
func CostVarianceIn(vs ...*decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldCostVariance, vs...))
}

// CostVarianceNotIn applies the NotIn predicate on the "cost_variance" field.
func CostVarianceNotIn(vs ...*decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldCostVariance, vs...))
}

// CostVarianceGT applies the GT predicate on the "cost_variance" field.
func CostVarianceGT(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldCostVariance, v))
}

// CostVarianceGTE applies the GTE predicate on the "cost_variance" field.
func CostVarianceGTE(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldCostVariance, v))
}

// CostVarianceLT applies the LT predicate on the "cost_variance" field.
func CostVarianceLT(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldCostVariance, v))
}

// CostVarianceLTE applies the LTE predicate on the "cost_variance" field.
func CostVarianceLTE(v *decimal.Decimal) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldCostVariance, v))
}

// CostVarianceIsNil applies the IsNil predicate on the "cost_variance" field.
func CostVarianceIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldCostVariance))
}

// CostVarianceNotNil applies the NotNil predicate on the "cost_variance" field.
func CostVarianceNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldCostVariance))
}

// BillingStatusEQ applies the EQ predicate on the "billing_status" field.
func BillingStatusEQ(v BillingStatus) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldBillingStatus, v))
}

// BillingStatusNEQ applies the NEQ predicate on the "billing_status" field.
func BillingStatusNEQ(v BillingStatus) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldBillingStatus, v))
}

// BillingStatusIn applies the In predicate on the "billing_status" field.
func BillingStatusIn(vs ...BillingStatus) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldBillingStatus, vs...))
}

// BillingStatusNotIn applies the NotIn predicate on the "billing_status" field.
func BillingStatusNotIn(vs ...BillingStatus) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldBillingStatus, vs...))
}

// BillingReferenceEQ applies the EQ predicate on the "billing_reference" field.
func BillingReferenceEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldBillingReference, v))
}

// BillingReferenceNEQ applies the NEQ predicate on the "billing_reference" field.
func BillingReferenceNEQ(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldBillingReference, v))
}

// BillingReferenceIn applies the In predicate on the "billing_reference" field.
func BillingReferenceIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldBillingReference, vs...))
}

// BillingReferenceNotIn applies the NotIn predicate on the "billing_reference" field.
func BillingReferenceNotIn(vs ...string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldBillingReference, vs...))
}

// BillingReferenceGT applies the GT predicate on the "billing_reference" field.
func BillingReferenceGT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldBillingReference, v))
}

// BillingReferenceGTE applies the GTE predicate on the "billing_reference" field.
func BillingReferenceGTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldBillingReference, v))
}

// BillingReferenceLT applies the LT predicate on the "billing_reference" field.
func BillingReferenceLT(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldBillingReference, v))
}

// BillingReferenceLTE applies the LTE predicate on the "billing_reference" field.
func BillingReferenceLTE(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldBillingReference, v))
}

// BillingReferenceContains applies the Contains predicate on the "billing_reference" field.
func BillingReferenceContains(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContains(FieldBillingReference, v))
}

// BillingReferenceHasPrefix applies the HasPrefix predicate on the "billing_reference" field.
func BillingReferenceHasPrefix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasPrefix(FieldBillingReference, v))
}

// BillingReferenceHasSuffix applies the HasSuffix predicate on the "billing_reference" field.
func BillingReferenceHasSuffix(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldHasSuffix(FieldBillingReference, v))
}

// BillingReferenceIsNil applies the IsNil predicate on the "billing_reference" field.
func BillingReferenceIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldBillingReference))
}

// BillingReferenceNotNil applies the NotNil predicate on the "billing_reference" field.
func BillingReferenceNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldBillingReference))
}

// BillingReferenceEqualFold applies the EqualFold predicate on the "billing_reference" field.
func BillingReferenceEqualFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEqualFold(FieldBillingReference, v))
}

// BillingReferenceContainsFold applies the ContainsFold predicate on the "billing_reference" field.
func BillingReferenceContainsFold(v string) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldContainsFold(FieldBillingReference, v))
}

// PollAttemptsEQ applies the EQ predicate on the "poll_attempts" field.
func PollAttemptsEQ(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldPollAttempts, v))
}

// PollAttemptsNEQ applies the NEQ predicate on the "poll_attempts" field.
func PollAttemptsNEQ(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldPollAttempts, v))
}

// PollAttemptsIn applies the In predicate on the "poll_attempts" field.
func PollAttemptsIn(vs ...int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldPollAttempts, vs...))
}

// PollAttemptsNotIn applies the NotIn predicate on the "poll_attempts" field.
func PollAttemptsNotIn(vs ...int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldPollAttempts, vs...))
}

// PollAttemptsGT applies the GT predicate on the "poll_attempts" field.
func PollAttemptsGT(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldPollAttempts, v))
}

// PollAttemptsGTE applies the GTE predicate on the "poll_attempts" field.
func PollAttemptsGTE(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldPollAttempts, v))
}

// PollAttemptsLT applies the LT predicate on the "poll_attempts" field.
func PollAttemptsLT(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldPollAttempts, v))
}

// PollAttemptsLTE applies the LTE predicate on the "poll_attempts" field.
func PollAttemptsLTE(v int) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldPollAttempts, v))
}

// NextPollAtEQ applies the EQ predicate on the "next_poll_at" field.
func NextPollAtEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldNextPollAt, v))
}

// NextPollAtNEQ applies the NEQ predicate on the "next_poll_at" field.
func NextPollAtNEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldNextPollAt, v))
}

// NextPollAtIn applies the In predicate on the "next_poll_at" field.
func NextPollAtIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldNextPollAt, vs...))
}

// NextPollAtNotIn applies the NotIn predicate on the "next_poll_at" field.
func NextPollAtNotIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldNextPollAt, vs...))
}

// NextPollAtGT applies the GT predicate on the "next_poll_at" field.
func NextPollAtGT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldNextPollAt, v))
}

// NextPollAtGTE applies the GTE predicate on the "next_poll_at" field.
func NextPollAtGTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldNextPollAt, v))
}

// NextPollAtLT applies the LT predicate on the "next_poll_at" field.
func NextPollAtLT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldNextPollAt, v))
}

// NextPollAtLTE applies the LTE predicate on the "next_poll_at" field.
func NextPollAtLTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldNextPollAt, v))
}

// NextPollAtIsNil applies the IsNil predicate on the "next_poll_at" field.
func NextPollAtIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldNextPollAt))
}

// NextPollAtNotNil applies the NotNil predicate on the "next_poll_at" field.
func NextPollAtNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldNextPollAt))
}

// LastPolledAtEQ applies the EQ predicate on the "last_polled_at" field.
func LastPolledAtEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldLastPolledAt, v))
}

// LastPolledAtNEQ applies the NEQ predicate on the "last_polled_at" field.
func LastPolledAtNEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldLastPolledAt, v))
}

// LastPolledAtIn applies the In predicate on the "last_polled_at" field.
func LastPolledAtIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldLastPolledAt, vs...))
}

// LastPolledAtNotIn applies the NotIn predicate on the "last_polled_at" field.
func LastPolledAtNotIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldLastPolledAt, vs...))
}

// LastPolledAtGT applies the GT predicate on the "last_polled_at" field.
func LastPolledAtGT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldLastPolledAt, v))
}

// LastPolledAtGTE applies the GTE predicate on the "last_polled_at" field.
func LastPolledAtGTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldLastPolledAt, v))
}

// LastPolledAtLT applies the LT predicate on the "last_polled_at" field.
func LastPolledAtLT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldLastPolledAt, v))
}

// LastPolledAtLTE applies the LTE predicate on the "last_polled_at" field.
func LastPolledAtLTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldLastPolledAt, v))
}

// LastPolledAtIsNil applies the IsNil predicate on the "last_polled_at" field.
func LastPolledAtIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldLastPolledAt))
}

// LastPolledAtNotNil applies the NotNil predicate on the "last_polled_at" field.
func LastPolledAtNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldLastPolledAt))
}

// SubmittedAtEQ applies the EQ predicate on the "submitted_at" field.
func SubmittedAtEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldSubmittedAt, v))
}

// SubmittedAtNEQ applies the NEQ predicate on the "submitted_at" field.
func SubmittedAtNEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldSubmittedAt, v))
}

// SubmittedAtIn applies the In predicate on the "submitted_at" field.
func SubmittedAtIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldSubmittedAt, vs...))
}

// SubmittedAtNotIn applies the NotIn predicate on the "submitted_at" field.
func SubmittedAtNotIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldSubmittedAt, vs...))
}

// SubmittedAtGT applies the GT predicate on the "submitted_at" field.
func SubmittedAtGT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldSubmittedAt, v))
}

// SubmittedAtGTE applies the GTE predicate on the "submitted_at" field.
func SubmittedAtGTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldSubmittedAt, v))
}

// SubmittedAtLT applies the LT predicate on the "submitted_at" field.
func SubmittedAtLT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldSubmittedAt, v))
}

// SubmittedAtLTE applies the LTE predicate on the "submitted_at" field.
func SubmittedAtLTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldSubmittedAt, v))
}

// SubmittedAtIsNil applies the IsNil predicate on the "submitted_at" field.
func SubmittedAtIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldSubmittedAt))
}

// SubmittedAtNotNil applies the NotNil predicate on the "submitted_at" field.
func SubmittedAtNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldSubmittedAt))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldCompletedAt))
}

// FailedAtEQ applies the EQ predicate on the "failed_at" field.
func FailedAtEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldEQ(FieldFailedAt, v))
}

// FailedAtNEQ applies the NEQ predicate on the "failed_at" field.
func FailedAtNEQ(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNEQ(FieldFailedAt, v))
}

// FailedAtIn applies the In predicate on the "failed_at" field.
func FailedAtIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIn(FieldFailedAt, vs...))
}

// FailedAtNotIn applies the NotIn predicate on the "failed_at" field.
func FailedAtNotIn(vs ...time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotIn(FieldFailedAt, vs...))
}

// FailedAtGT applies the GT predicate on the "failed_at" field.
func FailedAtGT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGT(FieldFailedAt, v))
}

// FailedAtGTE applies the GTE predicate on the "failed_at" field.
func FailedAtGTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldGTE(FieldFailedAt, v))
}

// FailedAtLT applies the LT predicate on the "failed_at" field.
func FailedAtLT(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLT(FieldFailedAt, v))
}

// FailedAtLTE applies the LTE predicate on the "failed_at" field.
func FailedAtLTE(v time.Time) predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldLTE(FieldFailedAt, v))
}

// FailedAtIsNil applies the IsNil predicate on the "failed_at" field.
func FailedAtIsNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldIsNull(FieldFailedAt))
}

// FailedAtNotNil applies the NotNil predicate on the "failed_at" field.
func FailedAtNotNil() predicate.GenerationJob {
	return predicate.GenerationJob(sql.FieldNotNull(FieldFailedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GenerationJob) predicate.GenerationJob {
	return predicate.GenerationJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GenerationJob) predicate.GenerationJob {
	return predicate.GenerationJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GenerationJob) predicate.GenerationJob {
	return predicate.GenerationJob(sql.NotPredicates(p))
}
